Edits for Test automation post 1
GoogleChrome/web.dev pull request #10302
Opened 2023-07-31 13:58 UTC by sofiayem

Ditto.

2023-07-31 14:09 UTC, jecfish commented on src/site/content/en/blog/ta-types/index.md
>  * [WebdriverIO](https://webdriver.io/)
somehow they don't show up in a list form

2023-07-31 14:10 UTC, jecfish approved these changes
All good except one small part.

2023-07-31 15:22 UTC, rachelandrew requested changes
This is in much better shape, can you just check the usage of "we" especially in the second half.

2023-07-31 15:22 UTC, rachelandrew commented on src/site/content/en/blog/ta-types/index.md
> +This series of guides will mostly focus on automated testing. However, you shouldn't focus on only one way of testing. Even if automation saves a lot of time and effort, humans and manual testing wil
Can we simply that epic sentence beginning with "Rather, test automation ..."?

2023-07-31 15:22 UTC, rachelandrew commented on src/site/content/en/blog/ta-types/index.md
> +As we get closer to answering the "how" question, we've already decided to do some manual testing. However, choosing and applying test automation types is a bit more challenging, though. The types of
Can we move this to second person? https://developers.google.com/style/person

2023-08-01 15:23 UTC, sofiayem commented
> This is in much better shape, can you just check the usage of "we" especially in the second half.

All fixed. PTAL one more time.

2023-08-02 10:09 UTC, rachelandrew approved these changes

2023-08-02 10:11 UTC, merged