More accurate storage info for Firefox
GoogleChrome/web.dev pull request #3839
Opened 2020-09-04 09:15 UTC by christianliebel

Changes proposed in this pull request:

Add more accurate maximum storage info for Firefox based on the already cited article: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Storage_limits

2020-09-08 17:57 UTC, jpmedley requested changes

2020-09-08 17:57 UTC, jpmedley commented on src/site/content/en/blog/storage-for-the-web/index.md
> +* Firefox allows the browser to use up to 50% of free disk space. An eTLD+1
```suggestion
* Firefox allows the browser to use up to 50% of free disk space. An 
  [eTLD+1](https://godoc.org/golang.org/x/net/publicsuffix)
```

2020-09-08 17:57 UTC, jpmedley commented on src/site/content/en/blog/storage-for-the-web/index.md
> +* Firefox allows the browser to use up to 50% of free disk space. An eTLD+1
Feel free to link to a different page.

2020-09-08 19:45 UTC, christianliebel commented on src/site/content/en/blog/storage-for-the-web/index.md
> +* Firefox allows the browser to use up to 50% of free disk space. An eTLD+1
That's perfect, thanks!

2020-09-09 13:56 UTC, jpmedley approved these changes

2020-09-09 13:56 UTC, merged