Initial german localization
GoogleChrome/web.dev pull request #3841
Opened 2020-09-04 12:29 UTC by eyecatchup

Changes proposed in this pull request:

- Add initial localization for German

2020-09-08 09:22 UTC, devnook requested changes

2020-09-08 09:22 UTC, devnook commented on src/site/content/de/404.njk
> +      Entschuldigung, die Siete konnte nicht gefunden werden.
Please sync it with the /en/404.md file (pls note change of the file extension)

2020-09-08 09:22 UTC, devnook commented on src/site/content/de/de.11tydata.js
> +    // translated: 'none',
This is needed for the UI to know that it's not an original post but a translation.

2020-09-08 09:22 UTC, devnook commented on src/site/content/de/feed.njk
> +<?xml version="1.0" encoding="utf-8"?>
Please sync with the /en/ equivalent.

2020-09-08 12:25 UTC, eyecatchup commented
@devnook Updated PR with requested changes.

2020-09-15 20:57 UTC, devnook approved these changes
Thanks @eyecatchup for your pull request! 
All files look fine.
We still need to run a few test on our side, to see how we can handle individual language contributions. I'll unblock and merge this pr as soon as we're ready to start accepting & serving de content on web.dev.

2020-10-19 18:53 UTC, robdodson commented
marking this as accepted so the stale bot will ignore it. We're getting close to launching our first test language so I'm hoping we can address this PR in the near future.

2020-10-20 12:31 UTC, eyecatchup commented
Nice. As soon as you're ready, I'll gladly translate much more content than I did with this first PR.

2020-10-20 12:47 UTC, Sifat1998 approved these changes

2021-02-26 21:49 UTC, conradkirschner commented
@robdodson any status update?

2021-03-02 22:41 UTC, robdodson commented
@conradkirschner we're continuing to work on it. We recently moved to firebase hosting which unlocks our ability to have different languages. We're working with a vendor to figure out what our initial set of docs to translate will be.

2021-03-03 06:56 UTC, conradkirschner commented
@robdodson so when I understood you correctly, you don't want a community translation? (Then I would unfollow this)

2021-03-06 00:36 UTC, robdodson commented
@conradkirschner no, not at the moment. We're going to start with vendor translated content and wait until we get to a good place with that before exploring community translations.

2021-03-06 00:37 UTC, robdodson commented
I think I'm going to close this for now, though I absolutely appreciate the work that people put into it. We're actively working on translations as we speak. COVID really slowed our team down but we're trying to ship some initial translations by late March, early April.

2021-03-06 00:37 UTC, closed without merging