[Wake Lock article] Document new WakeLockSentinel.released
GoogleChrome/web.dev pull request #3914
Opened 2020-09-22 08:31 UTC by tomayac

Changes proposed in this pull request:

- Document new `WakeLockSentinel.released`.
- Consistently use space (dash) in URL.

2020-09-22 13:50 UTC, jpmedley approved these changes

2020-09-22 14:03 UTC, jpmedley requested changes
This needs to cover that the new property isn't available until Chrome 87.

2020-09-22 14:03 UTC, jpmedley commented on src/site/content/en/blog/wake-lock/index.md
> +
```suggestion
This property is not yet universally available. As of this writing, it's 
supported in Chrome 87 or later and Chromium forks based on it. 
Check [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WakeLockSentinel/released#Browser_compatibility)
before using it.
 
```

2020-09-22 14:03 UTC, jpmedley commented on src/site/content/en/blog/wake-lock/index.md
> +
I wanted to say, "or caniuse", but it's not there yet.

2020-09-22 14:11 UTC, tomayac commented on src/site/content/en/blog/wake-lock/index.md
> +It is available as of Chrome&nbsp;87.
```suggestion
It is available as of Chrome&nbsp;87.

```

2020-09-22 15:10 UTC, jpmedley approved these changes

2020-09-22 15:11 UTC, jpmedley approved these changes

2020-09-22 15:14 UTC, tomayac commented
@kaycebasques, could you approve the redirect, please, and then merge? Joe has approved the content. Thanks!

2020-09-22 15:14 UTC, jpmedley commented
@kaycebasques Apparently I don't have the ability to approve redirects.

2020-09-23 16:51 UTC, robdodson approved these changes
redirect change LGTM

2020-09-23 21:50 UTC, merged