[Notification Triggers article] Revive Notification Triggers
GoogleChrome/web.dev pull request #3936
Opened 2020-09-24 07:59 UTC by tomayac

Changes proposed in this pull request:

- There will be a second OT.

2020-09-24 08:00 UTC, tomayac commented
@rknoll Please let me know once the new OT link is live. I assume we don't recycle the [old one](https://developers.chrome.com/origintrials/#/view_trial/6883752030435803137), do we?

2020-09-24 08:10 UTC, tomayac commented on src/site/content/en/blog/notification-triggers/index.md
> +| **4. Origin trial**                          | [In progress][ot]            |
```suggestion
| **4. Origin trial**                          | **[In progress][ot]**        |
```

2020-09-24 09:07 UTC, tomayac commented on src/site/content/en/blog/notification-triggers/index.md
> +  [obtained feedback](https://docs.google.com/document/d/1Nl1emEqxjTzPLNIAPiS26Vtq3mBdNyCxfMY6QwaD45s/edit)).
```suggestion
  to try out the proposed API, ran from Chrome&nbsp;80 to&nbsp;83.
  You can read the summary of the
  [obtained feedback](https://docs.google.com/document/d/1Nl1emEqxjTzPLNIAPiS26Vtq3mBdNyCxfMY6QwaD45s/edit))
  so far.
```

2020-09-24 22:27 UTC, jpmedley requested changes

2020-09-24 22:27 UTC, jpmedley commented on src/site/content/en/blog/notification-triggers/index.md
> +  [obtained feedback](https://docs.google.com/document/d/1Nl1emEqxjTzPLNIAPiS26Vtq3mBdNyCxfMY6QwaD45s/edit))
```suggestion
  [feedback obtained](https://docs.google.com/document/d/1Nl1emEqxjTzPLNIAPiS26Vtq3mBdNyCxfMY6QwaD45s/edit))
```

2020-09-25 09:32 UTC, tomayac commented on src/site/content/en/blog/notification-triggers/index.md
> +updated: 2020-09-24
```suggestion
updated: 2020-09-25
```

2020-09-25 09:33 UTC, tomayac commented
Please **do not merge** this yet, we're still waiting for the OT to show up. Thanks.

2020-09-25 14:36 UTC, jpmedley approved these changes
Waiting on OT. Please do not merge.

2020-09-25 15:41 UTC, jpmedley commented
@tomayac, are you just looking for someone to squash and merge?

2020-09-25 15:43 UTC, tomayac commented
> @tomayac, are you just looking for someone to squash and merge?

Waiting for Notification Triggers to re-appear on https://developers.chrome.com/origintrials/#/trials/active.

2020-09-25 15:49 UTC, rknoll commented
> Waiting for Notification Triggers to re-appear on https://developers.chrome.com/origintrials/#/trials/active.

Just appeared as active again 😃
https://developers.chrome.com/origintrials/#/view_trial/6883752030435803137

2020-09-28 08:19 UTC, merged

2020-09-28 08:19 UTC, tomayac commented
> > Waiting for Notification Triggers to re-appear on https://developers.chrome.com/origintrials/#/trials/active.
> 
> Just appeared as active again 😃
> https://developers.chrome.com/origintrials/#/view_trial/6883752030435803137

Thanks, @rknoll. Merged now.