Add File Handling article
GoogleChrome/web.dev pull request #3937
Opened 2020-09-24 10:41 UTC by tomayac

Changes proposed in this pull request:

- Add the article.
- This is still pending the OT info.
- [Google doc](https://docs.google.com/document/d/186TZWvonEqxITCp2D7EmUGopzuSxrjNeBGeV_Mvbakc/edit) for reviewing (for @jpmedley).

2020-09-25 01:58 UTC, jpmedley requested changes

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +I have added File Handling support to [Excalidraw][demo], a cartoon-style drawing app. When you
```suggestion
I have added file handling support to [Excalidraw][demo], a cartoon-style drawing app. When you
```

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +create a file with it and store it somewhere on your file system, you can now open the file via a
```suggestion
create a file with it and store it somewhere on your file system, you can open the file via a
```

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +double click, or a right click and then selecting "Excalidraw" in the context menu. You can check
```suggestion
double click, or a right click and then select "Excalidraw" in the context menu. You can check
```

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +There is a large category of attack vectors that are opened up by allowing websites access to files.
```suggestion
There is a large category of attack vectors that are opened by allowing websites access to files.
```

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +system capable of handling a given file type. In this case, some host operating systems may
```suggestion
The exception to this is when there are no applications on the host system for a given file
type. In this case, some host operating systems may
```

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +automatically promote the newly registered handler to become the default handler for that file type,
```suggestion
automatically promote the newly registered handler to the default handler for that file type,
```

2020-09-25 01:58 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +confirmation, and especially if a site is to become the default handler.
```suggestion
confirmation, especially if a site is to become the default handler.
```

2020-09-25 09:42 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +## What is the File Handling API? {: #what }
This comes straight from our [template](https://docs.google.com/document/d/1-yPBCOQcXczf7j9Hn47Ui4Cxqfslkln39rgIWD-AJK0/edit).

2020-09-25 09:43 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +- Game level design tools.
[Video game level editor](https://www.careerexplorer.com/careers/video-game-level-editor/#:~:text=A%20video%20game%20level%20editor%20creates%20the%20interactive%20architecture%20for,and%20variations%20that%20are%20needed.).

2020-09-25 09:43 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +The origin trial is expected to end in Chrome&nbsp;⛔️ (⛔️, 2020).
Yepp, versions pending.

2020-09-25 09:50 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +title: Open files with their proper app
```suggestion
title: Give web applications a way to register their ability to handle files
```

2020-09-25 09:50 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +title: Open files with their proper app
What do you think about the new title?

2020-09-25 14:38 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +title: Open files with their proper app
It gets the point of view right. I think think you can be pithier: "Let web applications be file handlers".

2020-09-25 14:39 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +## What is the File Handling API? {: #what }
I'll talk to Pete about it.

2020-09-25 14:40 UTC, jpmedley commented on src/site/content/en/blog/file-handling/index.md
> +- Game level design tools.
Oh, a level in a game. Duh. I'm not a gamer.

2020-09-25 14:43 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +title: Give web applications a way to register their ability to handle files
```suggestion
title: Let web applications be file handlers
```

2020-09-25 14:44 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +updated: 2020-09-24
```suggestion
date: 2020-09-25
# updated: 2020-09-25
```

2020-09-25 14:45 UTC, tomayac commented on src/site/content/en/blog/file-handling/index.md
> +title: Open files with their proper app
This is it :-) Thank you!

2020-10-22 13:42 UTC, tomayac commented
@kaycebasques @jpmedley This article can now be merged. We're publishing it as a Dev Trial article for now, since the Origin Trial will take a little longer to be ready. I will of course then update the article once we enter the OT phase.

2020-10-22 14:18 UTC, jpmedley approved these changes

2020-10-22 14:18 UTC, merged