Add serial dev tip
GoogleChrome/web.dev pull request #3975
Opened 2020-09-29 07:53 UTC by beaufortfrancois

Changes proposed in this pull request:

- Adds a new "Dev Tips" section to the Serial API section 
- Mention the internal page to debug Serial. 

FYI @reillyeon

Context: https://chromiumdash.appspot.com/commit/4f1bb9647664c4dd37d165d38b2161f1b121fb18

2020-09-29 16:23 UTC, jpmedley requested changes

2020-09-29 16:23 UTC, jpmedley commented on src/site/content/en/blog/serial/index.md
> +Debugging Serial in Chrome is easy with the internal page, `chrome://device-log`
```suggestion
Debugging the Serial API in Chrome is easy with the internal page, `chrome://device-log`
```

2020-09-29 16:23 UTC, jpmedley commented on src/site/content/en/blog/serial/index.md
> +  <img src="./device-log-page-screenshot.jpg" class="w-screenshot" alt="Screenshot of the internal page to debug Serial.">
```suggestion
  <img src="./device-log-page-screenshot.jpg" class="w-screenshot" alt="Screenshot of the internal page for debugging the Serial API.">
```

2020-09-29 16:23 UTC, jpmedley commented on src/site/content/en/blog/serial/index.md
> +  <figcaption class="w-figcaption">Internal page in Chrome to debug Serial.</figcaption>
```suggestion
  <figcaption class="w-figcaption">Internal page in Chrome for debugging the Serial API.</figcaption>
```

2020-09-29 16:23 UTC, jpmedley commented on src/site/content/en/blog/serial/index.md
> +Debugging Serial in the internal page is available in Chrome 87 and later.
```suggestion
The internal page supports debugging the Serial API in Chrome 87 and later.
```

2020-09-29 16:30 UTC, beaufortfrancois commented
Thank you @jpmedley!

2020-09-30 01:03 UTC, reillyeon approved these changes

2020-09-30 16:46 UTC, jpmedley approved these changes

2020-09-30 16:46 UTC, merged