Update third-party origin trials post: example registration screenshot, hero image alt text
GoogleChrome/web.dev pull request #4021
Opened 2020-10-07 17:21 UTC by samdutton

2020-10-07 20:29 UTC, jpmedley requested changes

2020-10-07 20:29 UTC, jpmedley commented on src/site/content/en/blog/third-party-origin-trials/index.md
> +     <img src="tpot-registration.png" alt="Chrome origin trials registration page for the Conversion Measurement API, with Third-party matching checkbox selected.">
```suggestion
     <img src="tpot-registration.png" alt="Chrome origin trials registration page for the Conversion Measurement API, with third-party matching checkbox selected.">
```

2020-10-08 10:44 UTC, samdutton commented on src/site/content/en/blog/third-party-origin-trials/index.md
> +     <img src="tpot-registration.png" alt="Chrome origin trials registration page for the Conversion Measurement API, with Third-party matching checkbox selected.">
Oops! Thanks Joe.

2020-10-08 21:51 UTC, jpmedley approved these changes

2020-10-08 21:51 UTC, merged