Added link to check latest
GoogleChrome/web.dev pull request #4059
Opened 2020-10-13 16:26 UTC by harsh1868

Added link of node site so that every time user can check any latest version by checking on it.

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- 
- 
-

2020-10-14 18:45 UTC, robdodson requested changes

2020-10-14 18:45 UTC, robdodson commented on README.md
> +You'll need a recent version of Node: v12.10 or higher. You can check latest version of [Node](https://nodejs.org/en/).
```suggestion
You'll need a recent version of [Node](https://nodejs.org/): v12.10 or higher.
```

2020-10-14 18:59 UTC, harsh1868 commented
@robdodson  please review.

2020-10-15 12:03 UTC, harsh1868 commented
@samthor  @robdodson  @devnook   please review.

2020-10-16 00:42 UTC, merged