[Idle Detection article] Add info about ended OT (Merge on Nov. 11, 2020)
GoogleChrome/web.dev pull request #4163
Opened 2020-11-02 08:49 UTC by tomayac

Changes proposed in this pull request:

- Add info about ended OT.

2020-12-03 08:41 UTC, tomayac commented on src/site/content/en/blog/idle-detection/index.md
> +updated: 2020-11-11
```suggestion
updated: 2020-12-03
```

2020-12-03 08:42 UTC, tomayac commented
Sorry, this fell through the cracks. It's information about an ended Origin Trial. @jpmedley or @kaycebasques, please approve and merge this when you have a chance.

2020-12-04 15:52 UTC, jpmedley commented
I requested changes that have not been addressed.

2020-12-04 16:08 UTC, tomayac commented
> I requested changes that have not been addressed.

@jpmedley I don't see any change requests.

2020-12-07 14:55 UTC, jpmedley requested changes
@tomayac apparently I neglected to submit them.

2020-12-07 15:34 UTC, tomayac commented on src/site/content/en/blog/idle-detection/index.md
> +  including the permission changes landed in Chrome&nbsp;87.
```suggestion
  including the permission changes landed in Chrome&nbsp;87,
  by flipping the [flag](#enabling-via-chrome:flags).
```

2020-12-07 15:34 UTC, tomayac commented on src/site/content/en/blog/idle-detection/index.md
> +  Interested developers can continue to test out the API locally,
Yes. I've added this info.

2020-12-07 15:35 UTC, tomayac commented on src/site/content/en/blog/idle-detection/index.md
> +updated: 2020-12-03
```suggestion
updated: 2020-12-07
```

2020-12-07 15:36 UTC, tomayac commented
> @tomayac apparently I neglected to submit them.

Addressed. PTAL. Thank you!

2020-12-07 19:16 UTC, jpmedley approved these changes

2020-12-07 19:16 UTC, merged