Indicate that noopener behavior is now default
GoogleChrome/web.dev pull request #4213
Opened 2020-11-12 15:07 UTC by ericlaw1979

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- 
- 
-

2020-12-13 00:21 UTC, ericlaw1979 commented
Unsure what's needed next? Maybe @petele knows?

2020-12-13 11:11 UTC, cleytontiagosorinho approved these changes
Sim

2020-12-14 14:47 UTC, petele commented
@kaycebasques or @jpmedley should be able to take a look this week. I know they were slammed last week with CDS and likely were prioritizing CDS content.

2020-12-14 15:32 UTC, jpmedley requested changes

2020-12-14 15:32 UTC, jpmedley commented on src/site/content/en/lighthouse-best-practices/external-anchors-use-rel-noopener/index.md
> +**Update** As of Chromium version 88, anchors with `target="_blank"` automatically get `noopener` behavior [by default](https://crbug.com?id=898942). Explicit specification of  `rel="noopener"` helps
```suggestion
{% Aside %}
As of Chromium version 88, anchors with `target="_blank"` automatically get
[`noopener` behavior by
default](https://www.chromestatus.com/feature/6140064063029248). Explicit
specification of  `rel="noopener"` helps protect users of legacy browsers
including Edge Legacy and Internet Explorer.
{% endAside %}
```

2020-12-14 18:49 UTC, jpmedley approved these changes

2020-12-14 18:49 UTC, merged