Update NFC article with spec changes
GoogleChrome/web.dev pull request #4259
Opened 2020-11-18 09:29 UTC by beaufortfrancois

This PR about the Web NFC article with latest spec and implementation changes:

- Replace `NDEFWriter.write` with `NDEFReader.write`
- Removes NDEF Scan options for filtering
- Removes NDEF Write option for ignoring read
- Marks chrome origin trial complete

There's still one "TODO" to link to a spec page (GH issue maybe) that lists changes after chrome origin trial.

2020-11-18 12:21 UTC, beaufortfrancois commented
@jpmedley Can you review?

2020-11-20 15:20 UTC, mihajlija commented on src/site/content/en/blog/nfc/index.md
> +missing, the promised returned by certain calls will reject. I'll provide
```suggestion
missing, the promise returned by certain calls will reject. I'll provide
```

2020-11-20 15:21 UTC, mihajlija approved these changes

2020-11-24 20:13 UTC, jpmedley requested changes

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
> +| 4. Origin trial                            | Complete                     |
Is NFC shipping in 88?

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
> +  During the origin trial phase, there was a `NDEFWriter` object that has been
```suggestion
  During the origin trial phase, there was an `NDEFWriter` object that has been
```

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
> +  read up on.
Link?

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
> +To experiment with Web NFC locally on Android, enable the
```suggestion
To experiment with Web NFC on Android, enable the
```

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
> +to "readingerror" events to be notified when incompatible NFC tags are in
```suggestion
to `readingerror` events to be notified when incompatible NFC tags are in
```

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
> +proximity range.
```suggestion
proximity.
```

2020-11-24 20:13 UTC, jpmedley commented on src/site/content/en/blog/nfc/index.md
>  example below shows you how to pass the `signal` of an AbortController through
```suggestion
example below shows you how to pass the `signal` of an `AbortController` through
```

2020-11-25 06:55 UTC, beaufortfrancois reviewed
Your feedback has been addressed. Thank you!

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
> +| 4. Origin trial                            | Complete                     |
Nope.

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
> +  During the origin trial phase, there was a `NDEFWriter` object that has been
Done.

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
> +  read up on.
Thanks for catching! Fixed.

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
> +To experiment with Web NFC locally on Android, enable the
Done

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
> +to "readingerror" events to be notified when incompatible NFC tags are in
Done. I've fixed `reading` as well above.

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
> +proximity range.
Done

2020-11-25 06:55 UTC, beaufortfrancois commented on src/site/content/en/blog/nfc/index.md
>  example below shows you how to pass the `signal` of an AbortController through
Done

2020-11-30 16:23 UTC, jpmedley approved these changes

2020-11-30 16:25 UTC, jpmedley commented
Is there any reason not to merge this now?

2020-11-30 16:28 UTC, beaufortfrancois commented
Yes. Spec changes have not been merged yet in Chromium.

2020-12-03 08:47 UTC, merged