Add macOS and Chrome OS support for barcode detection
GoogleChrome/web.dev pull request #4317
Opened 2020-11-30 14:03 UTC by beaufortfrancois

This PR makes sure macOS and Chrome OS support are mentioned for barcode detection.

2020-11-30 14:57 UTC, tomayac approved these changes
LGTM, approval.

It has always been hit and miss on macOS, breaking randomly with macOS or Chrome updates. I just verified it works again in Canary, so fingers crossed it stays.

2020-11-30 18:01 UTC, jpmedley requested changes

2020-11-30 18:01 UTC, jpmedley commented on src/site/content/en/blog/shape-detection/index.md
> +  Barcode detection has launched in Chrome 83.
```suggestion
  Barcode detection launched in Chrome 83.
```

2020-12-01 18:55 UTC, jpmedley approved these changes

2020-12-01 18:56 UTC, merged