Stories post - community submission
GoogleChrome/web.dev pull request #4327
Opened 2020-12-02 16:44 UTC by argyleink

adds a community submission to the post

2020-12-02 16:51 UTC, argyleink commented
https://deploy-preview-4327--web-dev-staging.netlify.app/building-a-stories-component/#remixes

2020-12-03 16:07 UTC, jpmedley requested changes

2020-12-03 16:07 UTC, jpmedley commented on src/site/content/en/blog/building-a-stories-component/index.md
> +1. [@geoffrich_](https://twitter.com/geoffrich_) with [Svelte](https://svelte.dev): [demo](https://svelte-stories.glitch.me) & [code](https://github.com/geoffrich/svelte-stories)
```suggestion
So far, I only know of one remix. Watch this spot or updates.

* [@geoffrich_](https://twitter.com/geoffrich_) with [Svelte](https://svelte.dev): [demo](https://svelte-stories.glitch.me) & [code](https://github.com/geoffrich/svelte-stories)
```

2020-12-03 16:26 UTC, jpmedley approved these changes

2020-12-03 16:26 UTC, merged