Update performance.measureMemory after renaming
GoogleChrome/web.dev pull request #4493
Opened 2021-01-20 11:49 UTC by ulan

The new name is performance.measureUserAgentSpecificMemory.

This also updates the examples to the new result format.

- 
- 
-

2021-01-20 17:50 UTC, jpmedley requested changes

2021-01-20 17:50 UTC, jpmedley commented on src/site/content/en/blog/coop-coep/index.md
> +returns `true`. `performance.measureUserAgentSpecificMemoryMemory` is ending its origin trial and is
```suggestion
returns `true`. `performance.measureUserAgentSpecificMemoryMemory()` is ending its origin trial and is
```

2021-01-20 17:50 UTC, jpmedley commented on src/site/content/en/blog/monitor-total-page-memory-usage/index.md
> +**January 20th, 2020**: `performance.measureUserAgentSpecificMemoryMemory` is renamed to `performance.measureUserAgentSpecificMemory`
```suggestion
**January 20th, 2020**: `performance.measureMemory()` is renamed to `performance.measureUserAgentSpecificMemory()`
```

2021-01-22 10:39 UTC, ulan commented on src/site/content/en/blog/coop-coep/index.md
> +returns `true`. `performance.measureUserAgentSpecificMemoryMemory` is ending its origin trial and is
Done.

2021-01-22 10:39 UTC, ulan commented on src/site/content/en/blog/monitor-total-page-memory-usage/index.md
> +**January 20th, 2020**: `performance.measureUserAgentSpecificMemoryMemory` is renamed to `performance.measureUserAgentSpecificMemory`
Oops. Thanks for catching this. Done.

2021-01-26 15:37 UTC, jpmedley approved these changes

2021-01-26 15:39 UTC, merged