[File System Access article] Add serialization instructions
GoogleChrome/web.dev pull request #4550
Opened 2021-01-28 14:29 UTC by tomayac

Changes proposed in this pull request:

- Add serialization instructions.

2021-01-28 14:31 UTC, tomayac commented
(Triggered via a [StackOverflow question](https://stackoverflow.com/questions/65928613/file-system-access-api-is-it-possible-to-store-the-filehandle-of-a-saved-or-loa/65938910#65938910) and https://github.com/GoogleChromeLabs/browser-fs-access/issues/30.)

2021-02-02 01:34 UTC, kaycebasques commented
Hello! This is an automated review. It updates automatically when code or GitHub comments in this pull request are created or updated.

## Staging URLs

For your convenience, here are direct links (on our staging site) to the content you created or updated:

* https://deploy-preview-4550--web-dev-staging.netlify.app/file-system-access/
## Requested changes

If there are any common problems with the content files you created or modified, they will be listed here.

### `src/site/content/en/blog/file-system-access/index.md`

* This file passed all of our automated Markdown audits.

<!-- Comment ID: reviewbot-automated-comment -->

2021-02-02 10:04 UTC, tomayac commented on src/site/content/en/blog/file-system-access/index.md
> +updated: 2021-01-28
```suggestion
updated: 2021-02-02
```

2021-02-02 10:05 UTC, tomayac commented
@kaycebasques @jpmedley This should be good to go. Thank you!

2021-02-02 20:30 UTC, jpmedley requested changes

2021-02-02 20:30 UTC, jpmedley commented on src/site/content/en/blog/file-system-access/index.md
> +The code snippet below shows storing and retrieving a file handle at an example.
```suggestion
The code example below shows storing and retrieving a file handle.
```

2021-02-03 10:46 UTC, tomayac commented
@jpmedley Comment addressed. Please approve and merge at your convenience.

2021-02-04 14:57 UTC, jpmedley approved these changes

2021-02-04 15:25 UTC, merged