Add Tabbed Application Mode article
GoogleChrome/web.dev pull request #4679
Opened 2021-02-16 14:31 UTC by tomayac

Fixes #4484

Changes proposed in this pull request:

- Add the article.

2021-02-24 19:17 UTC, jpmedley requested changes

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +an interface metaphor which is a set of unifying concepts used by graphical user interfaces (GUI) to
In Am English, 'that' is preferred for a restrictive clause, which this is. 

Or

'That' is preferred for the restrictive clause that this is.

The first sentence is about all restrictive clauses, so 'which' and a comma are used to indicate the subordinate clause does not refer to all restrictive clauses. The second phrasing is only about your sentence, so 'that' is used to indicate that the subordinate clause is restricting the number of things we're talking about.

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +  `"display": "browser"`, which does already exist and has a separate meaning (specifically, that
```suggestion
  the existing `"display": "browser"`, which has a separate meaning (specifically, that
```

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +- Communication apps can let the user have conversations in different rooms per tab.
```suggestion
- Communication apps that let the user have conversations in different rooms per tab.
```

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +- Reading apps can open article links in new in-app tabs.
```suggestion
- Reading apps that open article links in new in-app tabs.
```

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +- Communication apps can let the user have conversations in different rooms per tab.
Somewhere there's some writing advice about mixing up wording to keep a piece from being monotonous. In the case of lists, the rule to use parallel grammatical structures has priority. (Structures can be repeated for rhetorical effect too. See [the second paragraph of this](https://www.archives.gov/founding-docs/declaration-transcript).

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +- Communication apps can let the user have conversations in different rooms per tab.
That link predates most style guides and modern developments in language usage, so it seems to 'break' rules that I've been trying to share.

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +To use tabbed application mode, developers need to opt in their apps by setting a specific display
```suggestion
To use tabbed application mode, developers need to opt their apps in by setting a specific display
```

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +   contextmenu.
```suggestion
   context menu.
```

2021-02-24 19:17 UTC, jpmedley commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +Are you planning to use tabbed application mode? Your public support helps the Chrome team to
```suggestion
Are you planning to use tabbed application mode? Your public support helps the Chrome team
```

2021-02-25 13:44 UTC, tomayac commented on src/site/content/en/blog/tabbed-application-mode/index.md
> +date: 2021-02-16
```suggestion
date: 2021-02-25
```

2021-02-25 15:37 UTC, jpmedley approved these changes

2021-02-25 15:45 UTC, merged