Add Stack Overflow tag component
GoogleChrome/web.dev pull request #4721
Opened 2021-02-23 10:26 UTC by beaufortfrancois

Sometimes, a post is related to technologies that have "official" tags on Stack Overflow (e.g. `service-worker`).

This PR is adding a brand new Stack Overflow tag component that when used will show an "Ask on Stack Overflow" note the end of the post.

Fixes #4720

2021-02-23 12:20 UTC, tomayac commented on src/site/_includes/components/StackOverflow.js
> +      <a href="https://stackoverflow.com/search?q=%${tag}%5D+is%3Aquestion"
```suggestion
      <a href="https://stackoverflow.com/search?q=%5B${tag}%5D+is%3Aquestion"
```

Fix the percent encoding.

2021-02-23 12:21 UTC, tomayac commented on src/site/_drafts/_template-post/index.md
> +# post in a "Ask on Stack Overflow" note.
```suggestion
# post in an "Ask on Stack Overflow" note.
```

I know, NittyMcNitFace

2021-02-23 12:23 UTC, tomayac commented on src/site/content/en/handbook/yaml-front-matter/index.md
> +Sometimes, a post is related to technologies that have "official" tags on Stack Overflow
```suggestion
Sometimes, a post is related to technologies that have
["official" tags on Stack Overflow](https://stackoverflow.com/tags)
```

2021-02-23 12:23 UTC, tomayac commented on src/site/content/en/handbook/yaml-front-matter/index.md
> +(e.g. `service-worker`). When used, an "Ask on Stack Overflow" note will be shown at the end
```suggestion
(e.g. [`service-worker`](https://stackoverflow.com/questions/tagged/service-worker)).
When used, an "Ask on Stack Overflow" note will be shown at the end
```

2021-02-23 12:24 UTC, tomayac commented on src/site/_drafts/_template-post/index.md
> +# stack_overflow_tag: service-worker
```suggestion
# Find the official list of tags at https://stackoverflow.com/tags.
# stack_overflow_tag: service-worker
```

2021-02-23 12:26 UTC, tomayac commented on src/site/_includes/components/StackOverflow.js
> +        >browse a list of questions</a
```suggestion
        >browsing a list of questions</a
```

2021-02-23 12:26 UTC, tomayac requested changes
Just some additional improvements.

2021-02-23 13:45 UTC, beaufortfrancois commented on src/site/_includes/components/StackOverflow.js
> +      <a href="https://stackoverflow.com/search?q=%${tag}%5D+is%3Aquestion"
Thanks!

2021-02-23 13:45 UTC, beaufortfrancois commented on src/site/_includes/components/StackOverflow.js
> +        >browse a list of questions</a
Yep!

2021-02-23 13:45 UTC, beaufortfrancois commented on src/site/content/en/handbook/yaml-front-matter/index.md
> +Sometimes, a post is related to technologies that have "official" tags on Stack Overflow
Done

2021-02-23 13:45 UTC, beaufortfrancois commented on src/site/content/en/handbook/yaml-front-matter/index.md
> +(e.g. `service-worker`). When used, an "Ask on Stack Overflow" note will be shown at the end
Done.

2021-03-03 09:32 UTC, samthor reviewed
I'm quite supportive of this.

- should the image in the handbook be in the storage bucket
- is there a chance we might want to reference multiple tags, or is this YAGNI?

2021-03-03 09:41 UTC, tomayac commented on src/site/content/en/handbook/yaml-front-matter/index.md
> +date: 2021-02-23
```suggestion
date: 2021-03-03
```

2021-03-03 09:42 UTC, tomayac commented
> I'm quite supportive of this.

Yay!

> * should the image in the handbook be in the storage bucket

Done in https://github.com/GoogleChrome/web.dev/pull/4721/commits/d58a8053b2638fa5a00d84fbc3fe265a7066a45f.

> * is there a chance we might want to reference multiple tags, or is this YAGNI?

I think this is YAGNI. @beaufortfrancois?

2021-03-03 09:44 UTC, beaufortfrancois commented
> I think this is YAGNI. @beaufortfrancois?

+1

2021-03-05 23:33 UTC, robdodson approved these changes

2021-03-05 23:34 UTC, robdodson commented
I think this is good to land once the tests pass. @beaufortfrancois feel free to hit merge when you're ready.

2021-03-08 09:49 UTC, beaufortfrancois commented
Percy jobs still fail sadly. And I'm not sure if my change is related to this failure sadly ;(
```
> web.dev@3.0.0 snapshots /home/runner/work/web.dev/web.dev
> percy exec --config ./tools/percy/.percy.conf.yml -- node tools/percy/snapshots.js

 ›   Warning: Skipping visual tests. PERCY_TOKEN was not provided.
Error: net::ERR_CONNECTION_REFUSED at http://localhost:8080/
    at navigate (/home/runner/work/web.dev/web.dev/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:113:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/home/runner/work/web.dev/web.dev/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:88:21)
    at async Frame.goto (/home/runner/work/web.dev/web.dev/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:405:16)
    at async Page.goto (/home/runner/work/web.dev/web.dev/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:826:16)
    at async PercyScript.run.args (/home/runner/work/web.dev/web.dev/tools/percy/snapshots.js:97:7)
    at async Object.run (/home/runner/work/web.dev/web.dev/node_modules/@percy/script/index.js:25:7)
```

@robdodson May you be able to help?

2021-03-08 12:12 UTC, beaufortfrancois commented
I've recreated PR at https://github.com/GoogleChrome/web.dev/pull/4832 to make Percy jobs pass.

2021-03-08 12:31 UTC, merged