Gravity sensor: Adding release estimation date
GoogleChrome/web.dev pull request #4975
Opened 2021-03-26 13:13 UTC by arskama

Fixes #4966

Release estimation for Gravity Sensor API is
chrome 91. [1]

[1] https://chromestatus.com/features/5384099747332096

2021-03-29 07:54 UTC, beaufortfrancois commented
cc @tomayac

2021-03-29 08:09 UTC, tomayac approved these changes
LGTM, approval

Thanks!

2021-03-29 08:10 UTC, tomayac commented on src/site/content/en/blog/generic-sensor/index.md
> +{% Aside %} GravitySensor is expected to start shipping in Chrome 91. {% endAside %}
```suggestion
{% Aside %}
  `GravitySensor` is expected to start shipping in Chrome&nbsp;91.
{% endAside %}
```

2021-03-31 14:36 UTC, jpmedley requested changes

2021-03-31 14:36 UTC, jpmedley commented on src/site/content/en/blog/generic-sensor/index.md
> +  `GravitySensor` is expected to start shipping in Chrome&nbsp;91.
```suggestion
  `GravitySensor` is expected to ship in Chrome&nbsp;91.
```

2021-03-31 17:03 UTC, jpmedley approved these changes

2021-03-31 17:15 UTC, merged