Update PWA Install docs
GoogleChrome/web.dev pull request #5122
Opened 2021-04-20 14:40 UTC by petele

Changes proposed in this pull request:
- Updates the PWA Custom Install docs to better align with current best practices
- Updates analytics details for installability
- Adds more details about what happens when things fail

2021-04-21 15:42 UTC, jpmedley requested changes

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +helpful to provide an in-app experience to promote and enable installation of
```suggestion
But, some users don't realize that they can install your PWA, so it
helps to provide an in-app experience to promote and enable installation of
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +Let's take a look at the PWA install flow for Chrome and Edge, how you can
```suggestion
Consider the PWA install flow for Chrome and Edge, how you can
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +Let's take a look at the PWA install flow for Chrome and Edge, how you can
* Omit needless words (Shrunk and White)
* Avoid forms of 'we' (Our own handbook)

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +1. Browser checks the [installability criteria][criteria]
```suggestion
1. The browser checks the [installability criteria][criteria].
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +1. Browser checks the [installability criteria][criteria]
Please make these complete sentences.

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +To prevent confusion with your users, don't show your own custom install
```suggestion
To prevent user confusion, don't show your own custom install
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +of the install flow, log it to analytics.
```suggestion
of the install flow, and log it to analytics.
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +  ga('send', 'event', {
Should this function have a more formal name?

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +### Page handles click on in-app install element {: #click-in-app-install }
I'm having trouble processing this title. Part of the problem is two sequential prepositions (on-in). Grammatically it's fine. A prepositional phrase can function as an adjective, which is what 'in-app' is doing.

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +  // Identify which button was clicked, this should be unique for each button.
```suggestion
  // Identify which button was clicked. This should be unique for each button.
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +If the user clicks cancel, or dismiss, the install stops, the browser returns
```suggestion
If the user clicks cancel or dismiss, the install stops, the browser returns
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +If you're logging the event to analytics, like before, use category
```suggestion
If you're logging the event to analytics, like before, use the category
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +And set the event `value` to either `1` or `0`, depending on whether the user
Contrary to popular opinion, you can start a sentence with 'and'. You can also overuse it, which is why writing teachers discourage it. (It's a best practice that contributes to variety in sentence structure for goal of holding reader interest.) This is the third occurrence of this I've found and it's one of at least four. I would remove most of them. The same advice applies to 'but'.

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +gesture. And second, you can only call `prompt` once. But, as mentioned
```suggestion
First, to help prevent spamming users, calling `prompt()` requires a user
gesture. And second, you can only call `prompt()` once. But, as mentioned
```

2021-04-21 15:42 UTC, jpmedley commented on src/site/content/en/progressive-web-apps/customize-install/index.md
> +if more than one tab/window is open for the PWA, the `appinstalled` event is
```suggestion
if more than one tab or window is open for the PWA, the `appinstalled` event is
```

2021-05-03 18:53 UTC, kaycebasques commented
@petele this is waiting on you

2021-11-29 01:31 UTC, closed without merging