Add SXGs to /optimize-lcp
GoogleChrome/web.dev pull request #5143
Opened 2021-04-22 02:01 UTC by khempenius

cc @twifkak

2021-04-23 14:37 UTC, kaycebasques requested changes
@khempenius while you're here would you mind fixing those Markdown linting problems that the bot detected: https://github.com/GoogleChrome/web.dev/pull/5143#issuecomment-824482230

2021-04-23 14:37 UTC, kaycebasques commented on src/site/content/en/blog/optimize-lcp/index.md
> +Exchanges](https://web.dev/signed-exchanges).
```suggestion
Exchanges](/signed-exchanges).

```

(Re: the extra space) Some Markdown parsers need a space here to detect the new section heading

2021-04-26 16:59 UTC, kaycebasques commented
@khempenius you might be working on this now but just noting here that you've got a merge conflict

2021-04-29 00:37 UTC, twifkak commented
Was the merge conflict addressed by the latest commits?

2021-04-29 17:20 UTC, khempenius commented
@kaycebasques can you take a look at this? This is the first PR that I've run into pullapprove. I believe the merge conflict has been resolved.

2021-04-29 17:36 UTC, kaycebasques approved these changes

2021-04-29 17:37 UTC, kaycebasques commented
@khempenius you can merge when you're ready

2021-04-29 19:38 UTC, merged