Adds the borders lesson
GoogleChrome/web.dev pull request #5216
Opened 2021-04-30 07:21 UTC by rachelandrew

Fixes #4834 adds the borders learn css lesson.

2021-04-30 15:40 UTC, una requested changes

2021-04-30 15:57 UTC, andy-piccalilli commented on src/site/content/en/learn/css/borders/index.md
> +  id: 'abpyqeM'
Good catch

2021-04-30 15:59 UTC, andy-piccalilli commented on src/site/content/en/learn/css/borders/index.md
> +  border-image: url(https://assets.codepen.io/174183/border-image-frame.jpg);
I'm going to replace the demo with a screenshot of the demo because there's all sorts of same-origin stuff with border image, it seems

2021-04-30 16:08 UTC, andy-piccalilli approved these changes

2021-04-30 20:49 UTC, una approved these changes

2021-05-04 08:41 UTC, andy-piccalilli commented on src/site/content/en/learn/css/borders/index.md
> +src="image/VbAJIREinuYvovrBzzvEyZOpw5w1/HbXJEF76GpAQ5FhMeMgH.png",
Ah yeh same issue as other one. It's not really needed with the diag too 👍

2021-05-04 10:27 UTC, andy-piccalilli approved these changes

2021-05-04 15:33 UTC, una approved these changes

2021-05-04 15:34 UTC, merged