Adds layout assessments
GoogleChrome/web.dev pull request #5220
Opened 2021-04-30 20:47 UTC by argyleink

3 question pop quiz at the end 👍🏻

2021-05-02 19:24 UTC, rachelandrew commented on src/site/content/en/learn/css/layout/layout.assess.yml
> +      - content: block
I don't think this is right, it defines flow layout for the children https://www.w3.org/TR/css-display-3/#valdef-display-flow

2021-05-02 19:24 UTC, rachelandrew requested changes
I'm not sure about question 2 ...

2021-05-03 18:07 UTC, argyleink commented
> I'm not sure about question 2 ...

I'll replace it 👍🏻

2021-05-06 07:29 UTC, rachelandrew approved these changes

2021-05-06 07:29 UTC, rachelandrew commented on src/site/content/en/learn/css/layout/layout.assess.yml
> +        next like is needed."
```suggestion
        rationale: "While grid could put multiple paragraphs into columns, those
        columns would be their own columns, not flowing together from one to the
        next."
```

2021-05-06 07:29 UTC, rachelandrew commented on src/site/content/en/learn/css/layout/layout.assess.yml
> +        not it's order with other sibling elements"
```suggestion
        rationale: "Having these properties alone do not pull a box out of flow"
      - content: "It's no longer positioned based on its siblings positions"
        rationale: "A box with `position: absolute` for example, is now
        positioned with x and y coordinates based on the containing block, and
        not its order with other sibling elements"
```

2021-05-06 07:37 UTC, merged