[Text Fragment article] Add info about link generation and analytics
GoogleChrome/web.dev pull request #5228
Opened 2021-05-03 07:50 UTC by tomayac

Changes proposed in this pull request:

- Add info about programmatic link generation.
- Add info about  obtaining text fragment links for analytics.

2021-05-03 14:42 UTC, jpmedley requested changes

2021-05-03 14:42 UTC, jpmedley commented on src/site/content/en/blog/text-fragments/index.md
> +`fragment-generation-utils.js` that you can import and generate Text Fragment links with as
```suggestion
The [polyfill](https://github.com/GoogleChromeLabs/text-fragments-polyfill) contains a file
`fragment-generation-utils.js` that you can import and use to generate Text Fragment links. This is
```

2021-05-03 14:42 UTC, jpmedley commented on src/site/content/en/blog/text-fragments/index.md
> +`fragment-generation-utils.js` that you can import and generate Text Fragment links with as
The phrase was grammatically correct, but it sounded awkward to me.

2021-05-03 14:42 UTC, jpmedley commented on src/site/content/en/blog/text-fragments/index.md
> +as to not break those pages. There is an
```suggestion
so as to not break those pages. There is an
```

2021-05-03 14:42 UTC, jpmedley commented on src/site/content/en/blog/text-fragments/index.md
> +As a workaround for now, you can use the one-liner script below to extract
```suggestion
As a workaround for now, you can use the code below to extract
```

2021-05-03 14:42 UTC, jpmedley commented on src/site/content/en/blog/text-fragments/index.md
> +For sites that still wish to opt-out, we support a
```suggestion
For sites that wish to opt-out, Chrome supports a
```

2021-05-03 14:42 UTC, jpmedley commented on src/site/content/en/blog/text-fragments/index.md
> +header value that they can send, so user agents will not process Text Fragment URLs.
```suggestion
header value that they can send so user agents will not process Text Fragment URLs.
```

2021-05-10 10:29 UTC, tomayac commented
This should be good to go, but probably simply fell through the cracks.

2021-05-10 10:29 UTC, tomayac commented on src/site/content/en/blog/text-fragments/index.md
> +updated: 2021-05-03
```suggestion
updated: 2021-05-10
```

2021-05-11 06:39 UTC, merged