Adjust order of expected/actual in how to file a bug
GoogleChrome/web.dev pull request #5230
Opened 2021-05-03 14:31 UTC by petele

Changes proposed in this pull request:
- Adjusts order of 'expected' and 'actual' to match the Chromium bug template

2021-05-03 15:35 UTC, jpmedley requested changes

2021-05-03 15:35 UTC, jpmedley commented on src/site/content/en/blog/how-to-file-a-good-bug/index.md
> +   (logged when beforeinstallprompt.prompt()` resolves)
I don't understand what I'm looking at, so I don't know how to review it. Is this a procedure? A list of possible outputs from something?

2021-06-28 21:43 UTC, robdodson commented
@petele any thoughts on joe's comment?

2021-08-03 22:52 UTC, samthor commented
I don't think this needs content review, it's already been reviewed. This is just rearranging "expected" before "actual", to match most testing environments.

2021-08-03 22:52 UTC, samthor approved these changes

2021-08-04 14:55 UTC, jpmedley commented
@samthor I don't know who your content reviewer was, but it's possible he or she suffered from the "curse of knowledge". It may have passed because the reviewer knew what that section described before the reviewed the article. As someone who's never seen it before, I can't work it out.

2022-02-04 17:35 UTC, jpmedley commented
@petele @MichaelSolati This _really_ fell through the cracks. Do you want me to open a new PR?

2022-02-22 15:47 UTC, jpmedley requested changes
My 'suggestion' is to update the revision date. Other than that, this is good.

2022-02-22 15:47 UTC, jpmedley commented on src/site/content/en/blog/how-to-file-a-good-bug/index.md
> +updated: 2021-05-02
```suggestion
updated: 2022-02-22
```

2022-02-23 08:41 UTC, rachelandrew approved these changes

2022-02-23 08:41 UTC, rachelandrew commented on src/site/content/en/blog/how-to-file-a-good-bug/index.md
> +  [`<base href="https://original.url">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)
```suggestion
  [`<base href="https://original.url">`](https://developer.mozilla.org/docs/Web/HTML/Element/base)
```

2022-02-23 08:52 UTC, merged