Add Excalibur article
GoogleChrome/web.dev pull request #5300
Opened 2021-05-10 12:00 UTC by tomayac

Fixes #4858

Changes proposed in this pull request:

- Add article

2021-05-10 19:31 UTC, jpmedley requested changes
Because this is a transcript, I stayed away from changing wording. There are a couple of places where I felt I had to add or replace a word. My reasons are explained.

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +I click the **save** icon and enter a file name in the file save dialog. In Chrome, a browser that
```suggestion
I click the save icon and enter a file name in the file save dialog. In Chrome, a browser that
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +Now to saving. In Excalidraw, saving happens in a function called saveAsJSON. It first serializes
```suggestion
Now to saving. In Excalidraw, saving happens in a function called `saveAsJSON()`. It first serializes
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +fileSave. This function is likewise provided by the browser-fs-access library.
```suggestion
`fileSave()`. This function is likewise provided by the browser-fs-access library.
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +support the File System Access API, I can then even immediately save my changes, no need to go
```suggestion
support the File System Access API, I can then even immediately save my changes. No need to go
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +so when you double-clicked an .excalidraw file, the Excalidraw Electron app would open. Lipis, whom
```suggestion
so when you double-clicked an `.excalidraw` file, the Excalidraw Electron app would open. Lipis, whom
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +Handling. This is a regular macOS Big Sur installation. Now check out what happens when I
```suggestion
Handling. 

This is a regular macOS Big Sur installation. Now check out what happens when I
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +course double-clicking would work, too, it's just less dramatic to demonstrate in a screencast.
>it's just less dramatic to demonstrate in a screencast.

Stuff like this makes me think you should included some screen shots in this article. I don't want to hold up this PR though. If you do, we can merge it later.

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +the operating system. I do this in a new field called file_handlers in the Web App Manifest. Its
```suggestion
the operating system. I do this in a new field called `file_handlers` in the Web App Manifest. Its
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +value is an array of objects with an action and an accept property. The action determines the URL
```suggestion
value is an array of objects with an action and an `accept` property. The action determines the URL
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +The next step is to handle the file when the application launches. This happens in the launchQueue
```suggestion
The next step is to handle the file when the application launches. This happens in the `launchQueue`
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +interface where I need to set a consumer by calling, well, setConsumer. The parameter to this
```suggestion
interface where I need to set a consumer by calling, well, `setConsumer()`. The parameter to this
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +function is an asynchronous function that receives the launchParams. This launchParams object has a
```suggestion
function is an asynchronous function that receives the `launchParams`. This `launchParams` object has a
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +and from this file handle I get a blob that I then pass to our old friend loadFromBlob.
```suggestion
and from this file handle I get a blob that I then pass to our old friend `loadFromBlob()`.
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +onto the clipboard by passing a one-element array with a ClipboardItem with the blob to the
```suggestion
onto the clipboard by passing a one-element array with a `ClipboardItem` with the blob to the
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +navigator.clipboard.write function. For more information on what you can do with the clipboard API,
```suggestion
`navigator.clipboard.write()` function. For more information on what you can do with the clipboard API,
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +all other devices.
I'm thinking about images again.

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +I can even see all cursors move around. The Pixelbook's cursor moves steadily, since it's controlled
Or even a 5 second autoplay video.

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +APIs are being developed in the open, so everyone can chime in and have their voice heard! Talking
I realize this is a transcript, but the English idiom is "speaking of which".

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +> live in my Dropbox or Google Drive, not on my harddisk. I wish the File System Access API would
This has made it into Websters and Oxford as two words, which means we would need change Google properties to match if one word is more common.

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +early version of tabbed application mode in Excalidraw. This is how it looks like.
```suggestion
early version of tabbed application mode in Excalidraw. This is how it looks.
```

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +early version of tabbed application mode in Excalidraw. This is how it looks like.
This is one place where we must have an image before merging.

2021-05-10 19:31 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +have shown today pop up in your apps! My name is Tom, you can find me as
```suggestion
have shown today pop up in your apps. My name is Tom, you can find me as
```

2021-05-11 06:11 UTC, tomayac commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +filename that fill up my Downloads folder. But despite this downside, I can still save the file.
Fill is fine here. "I end up with multiple files […] that fill up my downloads folder".

2021-05-11 06:16 UTC, tomayac commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +types and extensions negotiation, the next step is to programmatically click the input element so
```suggestion
The fallback implementation relies on an input element of type "file". After the negotiation
of the to-be-accepted mime types and extensions,
the next step is to programmatically click the input element so
```

2021-05-11 06:18 UTC, tomayac commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +all other devices.
Images are still coming.

2021-05-11 13:46 UTC, jpmedley commented on src/site/content/en/blog/excalidraw-and-fugu/index.md
> +> live in my Dropbox or Google Drive, not on my harddisk. I wish the File System Access API would
FYI, dictionaries don't dictate. They document what's done.

2021-05-11 13:58 UTC, jpmedley commented
I can't approve this while it's in draft state.

2021-05-11 18:16 UTC, tomayac commented
@jpmedley All images (missing `alt` texts are a known issue, will fix tomorrow) and screencasts are done now. This is ready for full review.

2021-05-12 14:47 UTC, jpmedley commented
@tomayac I had considered what I already did a full review. I'm ok with whatever images you select. Merge as you see fit.

2021-05-12 14:47 UTC, jpmedley approved these changes

2021-05-12 14:56 UTC, merged