ES modules in service workers post
GoogleChrome/web.dev pull request #5343
Opened 2021-05-13 15:01 UTC by jeffposnick

This is a blog post describing the use of [ES modules in service workers](https://chromestatus.com/feature/4609574738853888), which shipped in M91.

It previously received a technical review out-of-band.

2021-05-13 19:37 UTC, jpmedley commented
@jeffposnick Can you please break this at 80 or 100n characters before I edit it?

2021-05-13 23:15 UTC, jeffposnick commented
I've reflowed the Markdown, Joe.

2021-05-14 14:11 UTC, jpmedley requested changes
I routinely request the fewest changes from your work. Nice job again.

2021-05-14 14:11 UTC, jpmedley commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +[Technology Preview 122 release](https://webkit.org/blog/11577/release-notes-for-safari-technology-preview-122/#:~:text=Added%20support%20for%20modules%20in%20Service%20Workers),
```suggestion
[Technology Preview 122 Release](https://webkit.org/blog/11577/release-notes-for-safari-technology-preview-122/#:~:text=Added%20support%20for%20modules%20in%20Service%20Workers),
```

2021-05-14 14:11 UTC, jpmedley commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +[Technology Preview 122 release](https://webkit.org/blog/11577/release-notes-for-safari-technology-preview-122/#:~:text=Added%20support%20for%20modules%20in%20Service%20Workers),
As a writer I think Apple is wrong in capitalizing 'release'. But they did and the rule is to follow their practice.

2021-05-14 14:11 UTC, jpmedley commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +version of Safari in a future release.
```suggestion
and developers should expect to see this functionality released in the stable
version of Safari in the future.
```

2021-05-14 14:11 UTC, jpmedley commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +At some point in the future, this restriction might be lifted, and dynamic ES
Omit needless words.

2021-05-14 14:11 UTC, jpmedley commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +service worker script through a
```suggestion
service worker script through an
```

2021-05-14 14:55 UTC, jeffposnick commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +using an `import('...')` statement. Inside of a service worker, only the static
I've updated to switch to that language.

2021-05-14 14:56 UTC, jeffposnick commented on src/site/content/en/blog/es-modules-in-sw/index.md
> +`install` phase. This restriction ensures that the browser knows about, and is
`importScripts()` isn't supported in client pages. It's only exposed in the `WorkerGlobalScope`: https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts

2021-05-14 17:54 UTC, jpmedley approved these changes

2021-05-17 12:14 UTC, merged