Refactoring and expanding the Media section
GoogleChrome/web.dev pull request #5545
Opened 2021-06-04 22:06 UTC by derekherman

We’re proposing to make [web.dev/media](https://web.dev/media) the single place for prescriptive guidance on how to build great media experiences. The site will tell developers what makes a great media experience, describe various tradeoffs, and provide strong recommendations where applicable. The content changes will happen in multiple phases with the initial phase being this pull request. In phase one we're focusing on reorganizing the various sections and updating the existing content to ensure a smooth transition between articles and consistent voice that builds with each progression through the various sections.

The “Concepts” section should be high-level describing all the foundational knowledge required to read the other two sections and be more about the theories i.e. concepts. The “Prepare media files for the web” section should build on the “Concepts” section and dive deeper into those topics with references and examples, and additionally move some of the “Concepts” content into this section while breaking up the cheat sheet into separate pages. The final section “Add media to a web page” should focus on doing, and dive much deeper into the previous topics. This is the section where we will add new content that describes the demo PWA that was built as part of this content revamp.

All of the pages have been read by multiple people and looked at for ways to improve the flow and build on what was already there. The majority of the original content is still intact with either a little manipulating or enhancement to connect it to the new structure and added pages. Every single page in the media section has been in some way edited. This PR is very extensive and represents the first phase as we continue to write more content that will dive deeper into areas like DRM, WebRTC, Picture-in-picture and many more.

Again the focus here is foundational and mainly on streaming video (VOD) and offline playback in relation to the demo PWA, while also diving a little bit deeper into all of the existing content including a lot more practical examples on how to manipulate video files with Shaka Packager and even a demo Docker file that makes it much easier to install for the average person. Phase two will be mostly new original pages and be much less focused on updating what is already there.

Tracking changes proposed in this pull request:

- [x] Add new authors
- [ ] Provide author images
- [ ] Update URLs referencing the new demo PWA, and repo, once it's been deployed to production
- [x] Restructure `/media` section content & page orders
- [x] Refactor `/media-experience`
- [x] Refactor `/media-file-basics`
- [x] Refactor `/media-application-basics`
- [x] Add `/media-streaming-basics`
- [x] Refactor `/prepare-media`
- [x] Refactor `/containers-and-codecs`
- [x] Refactor `/bitrate`
- [x] Refactor `/resolution`
- [x] Refactor `/media-cheat-sheet` and rename/redirect to`/media-conversion`
- [x] Add `/media-encryption`, include refactored content from `/media-cheat-sheet`
- [x] Refactor `/add-media`
- [x] Refactor `/video-and-source-tags`
- [x] Refactor `/media-accessibility`
- [x] Add `/media-frameworks`
- [x] Add `/pwa-with-offline-streaming`

2021-06-04 22:17 UTC, derekherman commented
@googlebot I consent.

2021-06-05 05:32 UTC, dero commented
@googlebot I consent.

2021-06-09 19:19 UTC, jpmedley requested changes

2021-06-09 19:19 UTC, jpmedley commented on src/site/content/en/media/video-and-source-tags/index.md
> +[`<source>`] to your web page. In addition to basics about these tags, this
```suggestion
[`<source>`] element. In addition to basics about these tags, this
```

2021-06-09 19:19 UTC, jpmedley commented on src/site/content/en/media/video-and-source-tags/index.md
> +article also explains attributes you should add to those tags to craft a good
```suggestion
article explains attributes you should add to those tags to craft a good
```

2021-06-09 19:19 UTC, jpmedley commented on src/site/content/en/media/video-and-source-tags/index.md
> +which instructs browsers to allow the user to control video playback, including
```suggestion
This instructs browsers to allow the user to control video playback, including
```

2021-06-09 19:19 UTC, jpmedley commented on src/site/content/en/media/video-and-source-tags/index.md
> +it's not a great user experience with the unresponsive version.
```suggestion
the unresponsive version isn't a great user experience.
```

2021-06-09 19:19 UTC, jpmedley commented on src/site/content/en/media/video-and-source-tags/index.md
>  * Firefox: Blocks all video and sound, but gives user the ability to relax these
```suggestion
* Firefox: Blocks all video and sound, but gives users the ability to relax these
```

2021-06-09 20:10 UTC, robdodson commented on src/site/content/en/media/bitrate/index.md
> +[Media application basics](/media-application-basics/#installing-applications-with-docker)
Not that I know of. It's free open source software so it should be ok for folks to use.

2021-06-16 21:53 UTC, derekherman commented on src/site/content/en/media/add-media/index.md
> +There is a lot of ground to cover in this section, let's get started by learning
@jpmedley Do you want to just remove the `let's` from the sentence?

2021-06-16 21:55 UTC, derekherman commented on src/site/content/en/media/bitrate/index.md
> +learned how to change the extension (container) and codec of a media file. In
That makes sense to me. I think swapping them would read better.

2021-06-16 21:55 UTC, derekherman commented on src/site/content/en/media/bitrate/index.md
> +In the previous [Containers and codecs](/containers-and-codecs/) article, we
Good catch

2021-06-16 22:07 UTC, derekherman commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +- The [Response constructor] tells us that there are several types of objects we
This change means we also need to change the Markdown link at the bottom of the page to reflect the update text.

2021-06-16 22:09 UTC, derekherman commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +- The `event.respondWith` method expects a `Response` object as a parameter.
@jpmedley not sure what this change is for. Why add `90` to the string?

2021-06-16 22:15 UTC, derekherman commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +```javascript
Shouldn't we also remove the space then? By my count the lines being highlighted don't line up with the file.

2021-06-16 22:19 UTC, derekherman commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +this creates a truly unique problem—media files can be very, *very* large. So
I feel the punctuation is actually correct here as it's more of a preference. Is there something in the handbook that says to use a colon over the em dash? We could definitely remove the double use of **very** though.

2021-06-16 22:23 UTC, derekherman commented on src/site/content/en/media/media-streaming-basics/index.md
> +This is valid, but doesn't actually work. Browsers don't natively support
Valid as in you can do it without errors but the browser can't do anything with it. At some point in the future I imagine you would be able to directly add the manifest to the `src` of the source element.

2021-06-16 22:27 UTC, derekherman commented on src/site/content/en/media/media-frameworks/index.md
> +version provided by Fastly. You can learn more on how to get the player set up
Probably. I'll look for the right link to add.

2021-06-16 22:28 UTC, derekherman commented on src/site/content/en/media/media-frameworks/index.md
> +According tho their website, [Video.js] is a web video player built from the
```suggestion
According to their website, [Video.js] is a web video player built from the
```

2021-06-16 22:31 UTC, derekherman commented on src/site/content/en/media/media-file-basics/index.md
> +**_Bitrate_** is the maximum number of bits used to encode one second of a stream.
```suggestion
**Bitrate** is the maximum number of bits used to encode one second of a stream.
```

2021-06-16 22:31 UTC, derekherman commented on src/site/content/en/media/media-file-basics/index.md
> +**_Resolution_** is the amount of information in a single frame of video, given as
```suggestion
**Resolution** is the amount of information in a single frame of video, given as
```

2021-06-16 22:41 UTC, derekherman commented on src/site/content/en/media/media-accessibility/index.md
> +`papayawhip` for all captions and all bold text colored `peachpuff`.
That a great point. I'll circle back on this.

2021-06-16 22:43 UTC, derekherman commented on src/site/content/en/media/bitrate/index.md
> +learned how to change the extension (container) and codec of a media file. In
```suggestion
learned how to change the container (extension) and codec of a media file. In
```

2021-06-16 22:43 UTC, derekherman commented on src/site/content/en/media/add-media/index.md
> +There is a lot of ground to cover in this section, let's get started by learning
```suggestion
There is a lot of ground to cover in this section, get started by learning
```

2021-06-16 22:56 UTC, derekherman commented
@jpmedley really excellent work finding all those issues. Sorry for the delay in getting back to you. I've been on vacation last week and this week. However, I know you are also going to be off next week so I sat down today and committed the bulk of the suggestions that could be merged easily. I'll do another pass tomorrow to fix the dates, merge conflicts, and any of the remaining unresolved suggestions. Thank you for reading the changes with a critical eye. Feels like you've found all the typos 😄  👍

2021-07-06 00:12 UTC, derekherman commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +```javascript
I see it starts at 0

2021-07-06 00:45 UTC, derekherman commented on src/site/content/en/media/media-frameworks/index.md
> +which framework is right for your project. In the next article we will discuss
The article this sentences is referencing is co-authored

2021-07-06 01:26 UTC, derekherman commented
@jpmedley I believe all the comments have been resolved. When you're able could you give this another look. As well, the workflow run needs to be approved so the lint and test can run.

Additionally, how do we add author photos?

2021-07-06 06:47 UTC, rachelandrew commented
@derekherman I'll leave this for Joe's approval but I've hit the button to run the workflows for you :)

2021-07-07 15:04 UTC, jpmedley commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +this creates a truly unique problem—media files can be very, *very* large. So
This one is from the Chicago Manual of Style, 17th edition, which is the Google standard. 6.61: "Between independent clauses it functions much like a semicolon". 6.85 suggests that colons can sometimes be substituted, but that rule does not cover the case of independent clauses.

2021-07-07 15:05 UTC, jpmedley commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +- The `event.respondWith` method expects a `Response` object as a parameter.
That was supposed to be '()', since this is a method.

2021-07-07 15:07 UTC, jpmedley commented
There are only two open items left, then we're done.

2021-07-07 20:56 UTC, derekherman commented on src/site/content/en/media/pwa-with-offline-streaming/index.md
> +- The `event.respondWith` method expects a `Response` object as a parameter.
Ah that makes more sense 👍

2021-07-07 21:21 UTC, derekherman commented
@jpmedley I've merged your change, thank you for the review. From my POV we need to add the author images, which I'm unsure on how to do that, and we also need to move the demo PWA repo to Google's GitHub and update the URLs. I have a call today with Rob Kochman so I'll bring that up. Otherwise, it appears like we're getting very close. Could you explain how to get author photos added?

2021-07-07 21:29 UTC, rkochman commented
I'm still working on getting the kino repo moved over. In the meantime, it looks like a Googler has to add your author image to the CDN for it to work on web.dev. Send me one that's 384x384, and I can do it.

2021-07-13 23:46 UTC, MichaelSolati commented
@derekherman we've made a big change to how we handle author data, would you like me to create a pr to your branch making the changes?

2021-07-27 20:46 UTC, derekherman commented
@MichaelSolati sorry I missed your comment. I've update the PR.

2021-07-27 20:49 UTC, derekherman commented
@rkochman has there been any movement on transferring the PWA repository?

2021-07-29 16:53 UTC, jpmedley approved these changes

2021-07-29 16:54 UTC, jpmedley commented
Are we ready to take this out of draft status?

2021-07-30 21:54 UTC, derekherman commented
@jpmedley the only thing left is for the PWA repo on GitHub to be transferred and then update the links in the markdown. We could take it out of draft but it still shouldn't be merged until that happens.

2021-08-02 13:40 UTC, jpmedley commented
Let's leave it in draft. That will prevent accidental merge.

2021-08-06 01:09 UTC, derekherman commented
@jpmedley this is now ready for review to be merged.

2021-08-16 17:11 UTC, merged