URLPattern article
GoogleChrome/web.dev pull request #5780
Opened 2021-07-09 18:42 UTC by jeffposnick

This PR includes a description of the `URLPattern` feature, which will be available behind a flag in Chrome 93.

@wanderview has already provided and out-of-band engineering review of this text, and @jpmedley has provided initial editorial feedback (but plans on doing another pass).

Publication is currently blocked on an upcoming release of the `urlpattern-polyfill`.

2021-07-20 19:16 UTC, jpmedley requested changes

2021-07-21 18:07 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +`URLPattern`'s syntax is a superset of what `path-to-regexp` supports, as
Fixed.

2021-07-21 18:08 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +`URLPattern` supports a fairly unique feature among routing libraries: matching
I'm going to go with "uncommon."

2021-07-21 18:10 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +`'about\\:blank'` when provided as a string.
Looking at the HTML generated, it's correct as-is:

![Screen Shot 2021-07-21 at 2 09 31 PM](https://user-images.githubusercontent.com/1749548/126538392-e233036f-1082-410c-8ff8-9cfed179bfca.png)

2021-07-21 18:22 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +the same as an equivalent `URLPattern` object created with an object. The
I can change "`URLPattern` object" to "`URLPattern`" so that it's less clunky.

2021-07-21 18:24 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +`exec()` returns detailed information about the match along with capture groups,
They do—I _think_ that's covered sufficiently by the `{% Aside %}` in the next section, which is more explicit about those parallels with `RegExp` behavior.

Do you want me to move up that `{% Aside %}` to make that parallel clearer, earlier?

2021-07-21 19:03 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +corresponding URL property, like `pathname`.
Sorry, I can see how the currently phrasing is confusing.

I've reworded this section. Let me know if it helps.

2021-07-21 19:03 UTC, jeffposnick commented on src/site/content/en/blog/urlpattern/index.md
> +changes to the current `location` and creates a corresponding piece of DOM to
I've removed the monospacing.

2021-07-21 19:04 UTC, jeffposnick commented
Please take another look, @jpmedley

2021-07-22 13:53 UTC, jpmedley approved these changes
Remember to change the publish date you this gets published.

2021-07-22 15:10 UTC, jeffposnick commented
Thanks, Joe!

2021-07-22 15:26 UTC, merged