generate x-frame-options and csp equivalent
GoogleChrome/web.dev pull request #5826
Opened 2021-07-20 00:43 UTC by samthor

Disallow iframing web.dev (except self iframing). This adds the CSP header as well as the fallback X-Frame-Options header.

2021-07-20 14:54 UTC, adamraine requested changes

2021-07-20 14:54 UTC, adamraine commented on firebase-config.js
> +      `frame-ancestors: 'self'; ` +
```suggestion
      `frame-ancestors 'self'; ` +
```

2021-07-22 02:00 UTC, samthor commented
PTAL

2021-07-22 02:15 UTC, adamraine approved these changes
LGTM

2021-07-22 13:42 UTC, merged