Mention @slightlyoff's blog posts for automating `contain-intrinsic-size`
GoogleChrome/web.dev pull request #5833
Opened 2021-07-21 19:08 UTC by kurtextrem

In my opinion a major pain point of most blog posts is they give info about how to combat drawbacks of nice features (such as `content-visibility: auto` and the scrollbar problem, which is fixed by `contain-intrinsic-size`) but without mentioning how you can implement this in larger scale. 
It is very rare that a dev has time to add (and maintain!) sizes of elements. So, as @slightlyoff has created blog-posts about the topic already, I figured mentioning those (as they contain code that is ready to be implemented) gives developers an easer time implementing `contain-intrinsic-size` and `content-visibility: auto`.

Changes proposed in this pull request:

- Add a short sentence to @slightlyoff's blog posts about automatically setting `contain-intrinsic-size` by utilizing `IntersectionObserver` and `MutationObserver`

This is my first PR here, so I'm happy to get feedback on how to improve wording if needed :)

2021-07-23 05:48 UTC, rachelandrew commented on src/site/content/en/blog/content-visibility/index.md
> +the correct sizes inline. [Alex Russel](https://twitter.com/slightlylate) explains
```suggestion
the correct sizes inline. [Alex Russell](https://twitter.com/slightlylate) explains
```

2021-07-23 05:52 UTC, rachelandrew commented on src/site/content/en/blog/content-visibility/index.md
> +
```suggestion
{% Aside %}
We can use `IntersectionObserver` and `MutationObserver` to set
the correct sizes inline for each element. [Alex Russell](https://twitter.com/slightlylate) explains
how this works in [`content-visibility` without jittery scrollbars](https://infrequently.org/2020/12/content-visibility-scroll-fix/), and [Resize-Resilient `content-visibility` Fixes](https://infrequently.org/2020/12/resize-resilient-deferred-rendering/).
{% endAside %}
```

2021-07-23 05:53 UTC, rachelandrew requested changes
I've made a suggestion for improved wording.

2021-07-23 08:03 UTC, kurtextrem commented
Thank you so much, sounds great :)

2021-07-23 19:40 UTC, mihajlija approved these changes

2021-07-26 20:41 UTC, merged

2021-07-27 07:38 UTC, kurtextrem commented
Thank you!! 🎊