Replace "TWA" to "PWA"
GoogleChrome/web.dev pull request #5885
Opened 2021-07-27 04:01 UTC by Oliverlin67

misspelled word

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- 
- 
-

2021-07-27 04:02 UTC, Oliverlin67 commented
> 感謝您的拉取請求。看起來這可能是您對 Google 開源項目的第一個貢獻（如果不是，請查看下面的幫助）。在我們查看您的拉取請求之前，您需要簽署一份貢獻者許可協議 (CLA)。
> 
> 📝 **請訪問https://cla.developers.google.com/進行簽名。**
> 
> 簽署（或解決任何問題）後，請在此處回复`@googlebot I signed it!`，我們將對其進行驗證。
> 
> #### 如果您已經簽署了 CLA，該怎麼辦
> ##### 個人簽名者
> * 可能我們沒有您的 GitHub 用戶名，或者您在提交時使用了不同的電子郵件地址。檢查[您現有的 CLA 數據](https://cla.developers.google.com/clas)並驗證您的[電子郵件是否設置在您的 git commits 上](https://help.github.com/articles/setting-your-email-in-git/)。
> 
> ##### 企業簽署人
> * 您的公司有一個聯繫人，負責決定哪些員工有權參與。要求將您的 POC 添加到授權貢獻者組中。如果您不知道您的聯繫人是誰，請讓 Google 項目維護者轉至[go/cla#troubleshoot](http://go/cla#troubleshoot)（[公共版](https://opensource.google/docs/cla/#troubleshoot)）。
> * 用於將您註冊為授權貢獻者的電子郵件必須是用於 Git 提交的電子郵件。檢查[您現有的 CLA 數據](https://cla.developers.google.com/clas)並驗證您的[電子郵件是否設置在您的 git commits 上](https://help.github.com/articles/setting-your-email-in-git/)。
> * 用於將您註冊為授權貢獻者的電子郵件也必須[附在您的 GitHub 帳戶中](https://github.com/settings/emails)。
> 
> ℹ️ **Google 員工：[前往此處](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2FGoogleChrome%2Fweb.dev%2Fpull%2F5885)了解更多信息**。
@googlebot I signed it!

2021-07-30 00:33 UTC, robdodson commented
I think the spelling may be intentionally referring to TWA (Trusted Web Activity). @petele can you confirm?

2021-08-03 15:11 UTC, mihajlija approved these changes

2021-08-03 15:12 UTC, mihajlija requested changes
Paging @petele

2021-08-04 13:25 UTC, Oliverlin67 commented
Sorry for taking up your time,

2021-08-19 22:24 UTC, samthor commented
Yeah, I think this is intentionally "TWA", but the document around it doesn't really describe this case.

Chrome supports `display-mode: standalone` so it will win. If it's not standalone then it's not really what the user might think of as a PWA—it'll still have a nav bar and so on. I haven't spun up a TWA lately so I'm not entirely clear on the referrer though.

@petele is out, I'll ping him next week

2021-09-11 00:46 UTC, samthor commented
From Pete: "short answer, nope.".

2021-09-11 00:46 UTC, closed without merging