New Post: 2021 Scroll Survey Report
GoogleChrome/web.dev pull request #5892
Opened 2021-07-28 16:27 UTC by argyleink

Fixes #5622

To do:
- [ ] use the web.dev cdn to host the report link
- [ ] get final reviews

2021-07-29 06:58 UTC, rachelandrew requested changes
I've done some copy editing on this, the main thing is that it is currently missing an image.

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +interact within scroll.
```suggestion
Some of the survey questions asked about using certain APIs with a possible
answer of Yes, No, or "today I learned." One notable piece of feedback was the
number of people who reported learning about `touch-action` from the survey, as
it's a critical property when building custom touch gestures that need to
interact within scroll.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +    where after 60 it's begins at 0 again
```suggestion
    The video shows cyclical seconds scrolling, <br>
    after 60 seconds it begins at 0 again.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +scrollable areas.
```suggestion
Respondents felt strongly about the importance of scrollable areas, 
giving another signal about the struggles required to deliver high-quality scrolling.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +high difficulty, which indicates to us an area needing attention.
```suggestion
Two-thirds of respondents deliver infinite scroll in their web work, and an equal
amount report it's difficult to do. Another example of high usage paired with
high difficulty, which indicates to us an area needing attention.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +difficulty.
```suggestion
Almost half of all respondents use scroll-orchestrated animations and half the
respondents find it difficult, once again linking high usage with difficulty.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +scroll linked animations, programmatic interfaces, voice integration, scroll
```suggestion
scroll-linked animations, programmatic interfaces, voice integration, scroll
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +the number of web compatibility issues, including scroll compatibility
```suggestion
The Chrome team has [declared a goal](https://web.dev/compat2021) to decrease
the number of web compatibility issues, including scroll compatibility.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +misunderstood.
```suggestion
forefront of international layout, and it's apparent it's underutilized or
misunderstood.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +satisfaction of scroll snap developer and user experience.
```suggestion
Usage of scroll snapping is growing, and developers have responded that they
want to use features interoperably with popular libraries and
plugins. Shrinking this gap between CSS and plugin libraries will help the
satisfaction of scroll snap developer and user experience.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +1. API availability / compatibility across browsers.
```suggestion
1. API availability and compatibility across browsers.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +38.7% somewhat dissatisfied", width="800", height="400" %}
```suggestion
38.7% somewhat dissatisfied.", width="800", height="400" %}
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      <b>extremely difficult</b>
```suggestion
      <b>extremely difficult</b>.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      with <b>web scrolling</b>
```suggestion
      with <b>web scrolling</b>.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      to  work with scrolling</b>
```suggestion
      to  work with scrolling</b>.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      to their work
```suggestion
      to their work.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      to do <b>gamepad</b> and <b>tab navigation</b>
```suggestion
      to do <b>gamepad</b> and <b>tab navigation</b>.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      from the survey
```suggestion
      from the survey.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      using <b>cyclical scrolling</b>
```suggestion
      using <b>cyclical scrolling</b>.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      <b>have used</b> carousels
```suggestion
      <b>have used</b> carousels.
```

2021-07-29 06:58 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +      <b>easy</b> to manage
```suggestion
      <b>easy</b> to manage.
```

2021-07-29 09:59 UTC, samdutton commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
I'm OK with not having one for this, but if we definitely need an image, we could get something from unsplash.com. I like the way it stands out (at the moment) without a thumbnail/hero.

2021-07-29 10:02 UTC, samdutton commented
Good edits @rachelandrew  — thank you!

2021-07-29 16:25 UTC, argyleink commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
yeah, i intentionally left an image out, thought it worked good. but am willing to find one if required 👍🏻

2021-07-30 07:27 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
I believe we can have a thumbnail without a hero, which would give it a sharing image without having the big image at the top of the post.

2021-07-30 07:27 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +survey](https://web.dev/2021-scroll-survey/) based on top reported issues from
```suggestion
survey](/2021-scroll-survey/) based on top reported issues from
```

2021-07-30 07:28 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +While [`content-visibility`](https://web.dev/content-visibility/) and
```suggestion
While [`content-visibility`](/content-visibility/) and
```

2021-07-30 07:30 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +1. [Logical properties](https://web.dev/learn/css/logical-properties/)
```suggestion
The Chrome team has [declared a goal](/compat2021) to decrease
the number of web compatibility issues, including scroll compatibility.

The first three compatibility issues to focus on:
1. Horizontal scrolling compatibility.
1. `overscroll-behavior` cross browser.
1. Removing prefixes from `-webkit-scrollbar` and following the standard.

### Education

The survey results showed that there needs to be more education around
`touch-action` and [logical
properties](/logical-property-shorthands/). The browser is at the
forefront of international layout, and it's apparent it's underutilized or
misunderstood.

Areas to focus on:
1. [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action)
1. [Logical properties](/learn/css/logical-properties/)
```

2021-07-30 07:31 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +  web](https://web.dev/compat2021/)
```suggestion
- [Scroll Survey
  Report](https://drive.google.com/file/d/10WXTJHCZmH0rXEh3J7z3ki96-f9SHs_R/view?usp=sharing&resourcekey=0-5b1y_6rZDhyt6Tkbz3FCzA)
- [Survey Announcement](/2021-scroll-survey/)
- [Mozilla DNA Reports](https://insights.developer.mozilla.org/)
- [Compat2021: Eliminating five top compatibility pain points on the
  web](/compat2021/)
```

2021-07-30 07:37 UTC, samdutton commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
Maybe a silly scroll pun: https://unsplash.com/photos/aXeVH4FcS1k

...or something more generic: https://unsplash.com/photos/Hcfwew744z4

2021-08-02 16:30 UTC, samdutton commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
@argyleink @rachelandrew 

Any preferences for a thumbnail?

2021-08-02 16:50 UTC, argyleink commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
i'm down with the pun 👍🏻

2021-08-02 17:05 UTC, samdutton commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +description: Get the 2021 Scroll Survey Report plus words from the Chrome team about how this impacts priorities and plans for Chromium and the web.
👍 I'll add it as thumbnail.

2021-08-02 17:44 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +- [Virtualized scroll.](https://github.com/tbranyen/hyperlist)
```suggestion
- [Positioning elements within scrollable areas](https://elad.medium.com/css-position-sticky-how-it-really-works-54cd01dc2d46)
- [Infinite scroll](https://blog.logrocket.com/infinite-scroll-techniques-in-react-adcfd7ff32bd/)
- [Scroll linked animation](https://greensock.com/scrolltrigger/)
- [Carousels](https://css-tricks.com/css-only-carousel/)
- [Scrollview padding](https://blog.alexandergottlieb.com/overflow-scroll-and-the-right-padding-problem-a-css-only-solution-6d442915b3f4)
- [Cyclical scroll](https://www.magictoolbox.com/magicscroll/integration/)
- [Virtualized scroll](https://github.com/tbranyen/hyperlist)
```

2021-08-02 17:48 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +scroll;`, the surface area of scroll APIs and options is large, spanning JS to
```suggestion
scroll;`, the surface area of scroll APIs and options is large, spanning JavaScript to
```

2021-08-02 17:54 UTC, rachelandrew commented on src/site/content/en/blog/2021-scroll-survey-report/index.md
> +alt: The unveiling of the new Torah display at Trinity International University, photo by Taylor Wilcox
```suggestion
alt: The unveiling of the new Torah display at Trinity International University, photo by Taylor Wilcox.
```

2021-08-02 17:55 UTC, rachelandrew approved these changes

2021-08-02 18:10 UTC, merged