[PWAs as URL handerl article] Make same origin rules clearer
GoogleChrome/web.dev pull request #5929
Opened 2021-08-05 11:22 UTC by tomayac

See https://github.com/WICG/pwa-url-handler/issues/29#issuecomment-892261526

Changes proposed in this pull request:

- Make same origin rules clearer.

2021-08-05 18:45 UTC, jpmedley requested changes

2021-08-05 18:45 UTC, jpmedley commented on src/site/content/en/blog/pwa-url-handler/index.md
> +{% Aside %} Apps that want to handle URLs that live on the _same_ origin than the PWA likewise need to
```suggestion
{% Aside %} Apps that want to handle URLs that live on the _same_ origin as the PWA likewise need to
```

2021-08-05 18:56 UTC, tomayac commented on src/site/content/en/blog/pwa-url-handler/index.md
> +{% Aside %} Apps that want to handle URLs that live on the _same_ origin than the PWA likewise need to
Oh, stupid me.

2021-08-06 09:47 UTC, mihajlija approved these changes

2021-08-06 09:49 UTC, merged