Blog gui challenges switch
GoogleChrome/web.dev pull request #5931
Opened 2021-08-05 16:43 UTC by argyleink

Fixes #5821

🔧  todo:
- [ ] final reviews
- [ ] finalize the date (probably 8/11/21)
- [ ] add final youtube embed

2021-08-09 08:00 UTC, rachelandrew requested changes
Some edits, a couple of things to remember for the future (as these were a lot of my changes). 

- Alt text should be a complete sentence. 
- When linking to web.dev, omit the domain.

2021-08-09 16:35 UTC, argyleink commented
> Some edits, a couple of things to remember for the future (as these were a lot of my changes).
> 
> * Alt text should be a complete sentence.
> * When linking to web.dev, omit the domain.

thanks Rachel! all the feedback has been integrated and updated ❤️

2021-08-10 22:15 UTC, argyleink commented
this post hopes to merge at 9:30am PDT on Wednesday 8/11 to be live and available by 10am. Thanks!

2021-08-11 06:34 UTC, rachelandrew commented on src/site/content/en/blog/building-a-switch-component/index.md
> +  Github](https://github.com/argyleink/gui-challenges)
```suggestion
### Resources

FInd the `.gui-switch` [source code on
  Github](https://github.com/argyleink/gui-challenges).
```

2021-08-11 06:36 UTC, rachelandrew approved these changes

2021-08-11 16:06 UTC, merged