All patterns
GoogleChrome/web.dev pull request #6025
Opened 2021-08-21 00:03 UTC by khempenius

cc @philipwalton

2021-08-24 07:06 UTC, samthor reviewed
I don't know how to review this. Is this imported from somewhere else?

2021-08-25 00:47 UTC, philipwalton commented
@samthor I have the context here and would be happy to review if you like.

2021-08-25 10:52 UTC, devnook requested changes
Please do not delete example patterns from example-set. They are needed to document how to build patterns, also in future. They do not appear on the /patterns/ site and are not indexed by search.

2021-08-25 13:55 UTC, devnook commented on src/site/content/en/patterns/index.md
> +description: A collection of code snippets to help you optimize for Web Vitals.
Patterns are intended not only for Web Vitals, but for other areas as well. Maybe move this description to the /patterns/web-vitals-patterns/index.md?

2021-09-07 22:21 UTC, philipwalton commented
> Please do not delete example patterns from example-set. They are needed to document how to build patterns, also in future. They do not appear on the /patterns/ site and are not indexed by search.

@devnook is that true? When I look at `/patterns/` I do see the example pattern set in the list.

2021-09-07 22:51 UTC, philipwalton requested changes
Thanks for putting this together, Katie! Looks great so far.

I made a few content suggestions. In addition to these I think we need to add some links to the existing Web Vitals content to make this pattern set discoverable.

We should probably add links to at least these two pages, potentially even some of the individual metrics pages or the "Optimize XXX" pages (specifically CLS, since most of these apply to CLS):

- https://web.dev/vitals/
- https://web.dev/learn-web-vitals/

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/index.md
> +description: Core Web Vitals friendly implementations of common UX patterns.
This description is showing up on the main `/patterns/` page, so this change should probably be reverted.

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/index.md
> +description: UX patterns are a frequent source of Core Web Vitals issues. These code samples show how to implement common UX patterns in a way that is Core Web Vitals friendly.
I think we should rephrase this to something like:

"A collection of common UX patterns optimized for Core Web Vitals. This collection includes patterns that are often tricky to implement without hurting your Core Web Vitals scores. You can use the code in these examples to help ensure your projects stay on the right track."

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/fonts/font-self-hosted/index.md
> +To further improve performace, consider using [font
s/performace/performance/

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/images/img-tag/index.md
> +  differently. In may cases, this can be fixed by adding `height: auto` or
s/may cases/many cases/

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/infinite-scroll/index.md
> +Infinite scroll is a UX pattern where content is continously added to the page
s/continously/continuously/

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/infinite-scroll/infinite-scroll/index.md
> +is performant way of monitoring the position and visibility of page page
s/is performant/is a performant/

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/notices-pattern-set/notice-sticky-footer/index.md
> +Sticky footers are a popular way of displaying notices. Notices placed in the footer are less likely to obscure page elements like navigation bars, branding, and banner ads. In addition, sticky foote
s/inserted in to/inserted into/

Also I think line wrapping needs to be applied to this.

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/video/video/index.md
> +  attributes specifies the image that should be displayed while a video is
s/attributes/attribute/

Right?

2021-09-07 22:51 UTC, philipwalton commented on src/site/content/en/patterns/web-vitals-patterns/video/video/index.md
> +  of the video is available, then uses this as the poster image; videos without
s/then uses/then use/

2021-09-08 08:54 UTC, devnook commented
@philipwalton You might see the example pattern set on the dev server (localhost or https://deploy-preview-6025--web-dev-staging.netlify.app/patterns/ ) but on prod it's not displayed (https://web.dev/patterns/).

2021-09-10 01:41 UTC, khempenius commented
@philipwalton this is ready for you to take a look at.

2021-09-10 06:24 UTC, devnook commented on src/site/_data/paths/learn-web-vitals.json
> +                    "title": "UX patterns optimzed for Core Web Vitals",
```suggestion
                    "title": "UX patterns optimized for Core Web Vitals",
```

2021-09-10 18:23 UTC, philipwalton approved these changes
Thanks @khempenius! Super excited to see these patterns go live!

2021-09-10 20:13 UTC, devnook commented
@khempenius please undelete the example pattern set before merging

2021-09-10 21:10 UTC, devnook approved these changes

2021-09-13 19:48 UTC, merged