minor text update
GoogleChrome/web.dev pull request #6058
Opened 2021-08-30 03:59 UTC by samthor

Fixes #6051

2021-08-30 06:59 UTC, rachelandrew requested changes
This has messed up the code highlighting in the main code section. If you compare the preview with the live article at https://web.dev/drag-and-drop/ I think the highlighted lines need adjusting.

The updated date should also be updated.

2021-08-30 07:58 UTC, samthor commented
I reworked this a bit and added a different section to call out adding thie handler.

2021-08-31 07:04 UTC, rachelandrew approved these changes
I think the "we do this above" comment is now redundant, otherwise lgtm.

2021-08-31 07:04 UTC, rachelandrew commented on src/site/content/en/blog/drag-and-drop/index.md
> +add an event listener for the `drop` event (we do this above, so you can fill it in).
```suggestion
add an event listener for the `drop` event.
```

2021-08-31 07:04 UTC, rachelandrew commented on src/site/content/en/blog/drag-and-drop/index.md
> +add an event listener for the `drop` event (we do this above, so you can fill it in).
now you've changed the structure I think we don't need this.

2021-08-31 07:34 UTC, merged