Translations - blog posts, docs [ES, JA, PT, RU, ZH, KO]
GoogleChrome/web.dev pull request #6139
Opened 2021-09-06 14:41 UTC by ilyaspiridonov

Translated by Alconost
Includes translations of blog posts and documentation, as well as some fixes in existing ES translations.

2021-09-07 19:08 UTC, jpmedley commented
@robdodson

2021-09-07 19:11 UTC, jpmedley approved these changes

2021-09-08 13:36 UTC, devnook requested changes
@ilyaspiridonov Can you please fix lint warnings?

2021-09-09 11:46 UTC, ilyaspiridonov commented
@devnook Lint tests seem to be in green now

2021-09-09 15:40 UTC, devnook commented
Hi @ilyaspiridonov ! The build is still broken. I'm taking a look now.

2021-09-09 16:30 UTC, devnook commented on src/site/content/ko/blog/defining-core-web-vitals-thresholds/index.md
> +<div class="w-stack w-stack--center w-stack--md">{% Img src="image/tcFciHGuF3MxnTr1y5ue01OGLBn2/ZZU8Z7TMKXmzZT2mCjJU.svg", alt="최대 콘텐츠풀 페인트 권장 임계값", width="400", height="350" %} {% Img src="image/tcF
These images are duplicated, I think. compare to: https://raw.githubusercontent.com/GoogleChrome/web.dev/main/src/site/content/en/blog/defining-core-web-vitals-thresholds/index.md

2021-09-09 16:50 UTC, devnook commented on src/site/content/ko/blog/defining-core-web-vitals-thresholds/index.md
> +<div class="w-stack w-stack--center w-stack--md">{% Img src="image/tcFciHGuF3MxnTr1y5ue01OGLBn2/ZZU8Z7TMKXmzZT2mCjJU.svg", alt="최대 콘텐츠풀 페인트 권장 임계값", width="400", height="350" %} {% Img src="image/tcF
```suggestion
```

2021-09-09 16:52 UTC, devnook commented on src/site/content/ko/blog/optimize-lcp/index.md
> +  <figcaption class="w-figcaption">페이지 로드 시 서비스 작업자 여부에 따른 최대 콘텐츠풀 분포 - <a href="https://philipwalton.com/articles/smaller-html-payloads-with-service-workers/">philipwalton.com</a></figcaption>
```suggestion
```

2021-09-09 18:53 UTC, devnook approved these changes

2021-09-09 18:53 UTC, merged