Storage Foundation: clarify interop
GoogleChrome/web.dev pull request #6275
Opened 2021-09-24 12:24 UTC by tomayac

Clarify interoperability between the two APIs.

2021-09-24 13:14 UTC, jpmedley requested changes

2021-09-24 13:14 UTC, jpmedley commented on src/site/content/en/blog/file-system-access/index.md
> +{% aside %} There exists no way of accessing a file stored through Storage Foundation API using
```suggestion
{% aside %} There exists no way of accessing a file stored through the Storage Foundation API using
```

2021-09-27 13:44 UTC, jpmedley approved these changes

2021-09-27 13:57 UTC, tomayac commented on src/site/content/en/blog/file-system-access/index.md
> +{% aside %} There exists no way of accessing a file stored through the Storage Foundation API using
```suggestion
{% Aside %} There exists no way of accessing a file stored through the Storage Foundation API using
```

2021-09-27 14:07 UTC, merged