LearnCSS: Text & Typography
GoogleChrome/web.dev pull request #6749
Opened 2021-11-09 17:20 UTC by camden

Changes proposed in this pull request:

- Add Typography module

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2021-11-09 17:39 UTC, camden commented
https://deploy-preview-6749--web-dev-staging.netlify.app/learn/css/typography/

2021-11-11 19:08 UTC, camden commented
@rachelandrew Can you please review this PR when you get a chance?

2021-11-12 08:12 UTC, rachelandrew requested changes
Copy editing, nothing major.

2021-11-12 08:12 UTC, rachelandrew commented on src/site/content/en/learn/css/typography/index.md
> +[`text-decoration-color`](https://developer.mozilla.org/docs/Web/CSS/text-decoration-color) sets the color of all decorations from `text-decoration-line`.
```suggestion
The [`text-decoration-color`](https://developer.mozilla.org/docs/Web/CSS/text-decoration-color) property sets the color of all decorations from `text-decoration-line`.
```

2021-11-12 23:30 UTC, camden commented
Thank you for the feedback, Rachel!

2021-11-15 23:26 UTC, una commented
@camden, I love this module!! 😄

2021-11-16 00:10 UTC, argyleink approved these changes
lgtm!

2021-11-18 19:33 UTC, camden commented
Assessment is now in the [preview build](https://deploy-preview-6749--web-dev-staging.netlify.app/learn/css/typography/). I also made some other minor edits to the doc. PTAL @rachelandrew @una @argyleink 🙏

2021-11-23 10:16 UTC, rachelandrew commented on src/site/content/en/learn/css/typography/index.md
> +date: 2021-11-09
```suggestion
date: 2021-11-23
```

2021-11-23 10:20 UTC, rachelandrew commented on src/site/content/en/learn/css/typography/index.md
> +* [MDN Fundamental text and font styling](https://developer.mozilla.org/docs/Learn/CSS/Styling_text/Fundamentals)
```suggestion
* [MDN Fundamental text and font styling](https://developer.mozilla.org/docs/Learn/CSS/Styling_text/Fundamentals).
```

2021-11-23 10:20 UTC, rachelandrew approved these changes

2021-11-23 10:21 UTC, rachelandrew commented
All lgtm, I've updated the date so I think we're ready to land this one today.

2021-11-23 18:01 UTC, merged