refactor(live-posts): rename `livePosts` to `isLive` and add new `livePosts` filter, fixes #6803
GoogleChrome/web.dev pull request #6804
Opened 2021-11-16 19:15 UTC by MichaelSolati

Fixes #6803

Changes proposed in this pull request:

- Rename `livePosts` to `isLive`
- Add `livePosts` filter/function that takes an array and filters it with the `isLive` function.
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2021-11-16 21:19 UTC, MichaelSolati commented
@devnook PTAL

2021-11-17 13:21 UTC, devnook requested changes

2021-11-17 13:21 UTC, devnook commented on .eleventy.js
> +const {livePosts} = require('./src/site/_filters/live-posts');
Please use default export and import without {} as all the filters above.

2021-11-17 13:21 UTC, devnook commented on src/site/_filters/live-posts.js
> +module.exports = {livePosts, isLive, isScheduledForTheFuture};
Please move isLive to it's own file.

2021-11-18 17:40 UTC, devnook approved these changes

2021-11-18 17:48 UTC, merged