Add SVGcode article
GoogleChrome/web.dev pull request #6829
Opened 2021-11-18 14:14 UTC by tomayac

Changes proposed in this pull request:

- Add the article.

2021-11-18 19:14 UTC, jpmedley requested changes

2021-11-18 19:14 UTC, jpmedley commented on src/site/content/en/blog/svgcode/index.md
> +              loop=true,
Please do likewise with the rest of your video "images".

2021-11-18 19:14 UTC, jpmedley commented on src/site/content/en/blog/svgcode/index.md
> +The Async Clipboard API recently has gained the ability to deal with SVG images as well, so you can
```suggestion
The Async Clipboard API has recently gained the ability to deal with SVG images as well, so you can
```

2021-11-18 19:14 UTC, jpmedley commented on src/site/content/en/blog/svgcode/index.md
> +Read up all the details on [file handling](/file-handling/) in article, and view the source code in
```suggestion
For more information, see [Let installed web applications be file handlers](/file-handling/), and view the source code in
```

2021-11-18 19:14 UTC, jpmedley commented on src/site/content/en/blog/svgcode/index.md
> +can become an essential tool for your image processing needs, alongside other amazing apps like
```suggestion
can become an essential tool for your image processing needs alongside other amazing apps like
```

2021-11-18 19:14 UTC, jpmedley commented on src/site/content/en/blog/svgcode/index.md
> +SVGcode is available at [svgco.de](https://svgco.de/), see what I did there? You can
```suggestion
SVGcode is available at [svgco.de](https://svgco.de/). See what I did there? You can
```

2021-11-19 10:14 UTC, tomayac commented on src/site/content/en/blog/svgcode/index.md
> +              loop=true,
It looks like an image, but it's technically still a `<video>`, and there is no `alt` attribute allowed on those. Instead, let me wrap all `{% Video %}` in `<figure>`.

2021-11-19 10:15 UTC, tomayac commented on src/site/content/en/blog/svgcode/index.md
> +              loop=true,
See above

2021-11-19 10:16 UTC, tomayac commented on src/site/content/en/blog/svgcode/index.md
> +[converted to Web Assembly](https://www.npmjs.com/package/esm-potrace-wasm), so it can be used in a
This required that I knew what I was doing, though. Maybe something for @RReverser?!

2021-11-19 10:16 UTC, tomayac commented on src/site/content/en/blog/svgcode/index.md
> +              loop=true,
See above.

2021-11-19 10:16 UTC, tomayac commented on src/site/content/en/blog/svgcode/index.md
> +              loop=true,
See above.

2021-11-19 10:17 UTC, tomayac commented on src/site/content/en/blog/svgcode/index.md
> +              loop=true,
See above.

2021-11-19 10:41 UTC, tomayac commented
Thanks, @jpmedley, for the review! PTAL!

2021-11-19 16:55 UTC, jpmedley approved these changes

2021-11-19 18:04 UTC, merged