Terra dark mode case study
GoogleChrome/web.dev pull request #6898
Opened 2021-11-27 22:20 UTC by demianrenzulli

Fixes #6653

Changes proposed in this pull request:

- Terra Dark Mode case study.
- New profile for co-author Guilherme Moser De Souza. 

cc // @rachelandrew @andreban

2021-11-30 10:35 UTC, rachelandrew requested changes
See comments inline, this PR crossed over the component code change so I've had a go at updating to the new components too so this one can be in the new layout.

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +</figure>
```suggestion
<figure>
  {% Img src="image/admin/Yh6SEoWDK1SbqcGjlL6d.png", alt="Android Q dark mode settings.", width="218", height="250" %}
  <figcaption>Android&nbsp;Q dark theme settings.</figcaption>
</figure>
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +This article will only cover the technique of applying a custom dark theme, provided by the developer. Chrome 96 has introduced an [origin trial](https://developer.chrome.com/blog/auto-dark-theme/#si
```suggestion
This article will only cover the technique of applying a custom dark theme, provided by the developer. Chrome 96 has introduced an [origin trial](https://developer.chrome.com/blog/auto-dark-theme/#sign-up-for-the-origin-trial) for "Auto Dark Themes" on Android, for which the browser applies an automatically generated dark theme to light themed sites, when the user has opted into dark themes in the operating system, without requiring the developer to provide styles for it. For more information about "Chrome Auto Dark Mode", check out [this article](https://developer.chrome.com/blog/auto-dark-theme/).
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +As a complement of this strategy they provide additional configuration options in the "settings" screen, where the user can decide if they explicitly prefer "light", "dark" or just rely on the underl
```suggestion
As a complement of this strategy they provide additional configuration options in the "settings" screen, where the user can decide if they explicitly prefer "light", "dark", or want to rely on the underlying device settings.
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +  <figcaption class="w-figcaption">Therra's dark theme, "Night Mode".</figcaption>
```suggestion
  <figcaption>Terra's dark theme, "Night Mode".</figcaption>
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +- **Mobile (Android):** While bounce rates remained similar, pages and sessions almost doubled (from 2.47 to 5.24) when users were exposed to a dark theme.
```suggestion
### Mobile (Android

While bounce rates remained similar, pages and sessions almost doubled (from 2.47 to 5.24) when users were exposed to a dark theme.
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +- **Desktop (Windows):** Both metrics improved when showing a dark theme: bounce rates went from 27.25% to 10.82% and pages per session almost tripled (from 3.7 to 9.99).
```suggestion
### Desktop (Windows)

Both metrics improved when showing a dark theme: bounce rates went from 27.25% to 10.82% and pages per session almost tripled (from 3.7 to 9.99).
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +layout: post-old
```suggestion
layout: post
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +</div>
```suggestion
<ul class="stats">
  <div class="stats__item">
    <p class="stats__figure">60<sub>%</sub></p>
    <p>Reduction in Bounce Rates</p>
  </div>
  <div class="stats__item">
    <p class="stats__figure">170<sub>%</sub></p>
    <p>More pages per session</p>
  </div>
</ul>
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +Dark Mode has [benefits](https://web.dev/prefers-color-scheme/#why-dark-mode) for user experience. Some people prefer it for aesthetic or accessibility reasons. It has  other advantages, such as pres
```suggestion
Dark Mode has [benefits](/prefers-color-scheme/#why-dark-mode) for user experience. Some people prefer it for aesthetic or accessibility reasons. It has  other advantages, such as preserving battery life in devices. Users can express that they prefer dark mode via a setting in their devices, [which depends on the operating system](/prefers-color-scheme/#activating-dark-mode-in-the-operating-system). For example, the following screenshot shows what the **Dark Theme** configuration option looks like in devices that run **Android Q**:
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +</figure>
```suggestion
<figure>
  {% Img src="image/26V1DWN36MZr3mUo8ChSBlCpzp43/TRqfCAmBe025456JyX1b.png", alt="Screenshot of Terra's light theme prompting the user to accept dark mode.", width="266", height="146" %}
  <figcaption>Terra shows a prompt to the user asking if they want to navigate in dark mode after detecting that they prefer dark in their devices.</figcaption>
</figure>
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +This is how Terra's "Night Mode" looks like:
```suggestion
<figure>
  {% Img src="image/26V1DWN36MZr3mUo8ChSBlCpzp43/B7g0uvq2QB0eWVjnuMAl.png", alt="Screenshots of Terra's configuration screen to opt in and out of dark mode.", width="480", height="417" %}
  <figcaption>Terra's themes configurations allow users to choose between "Dark" and "Light" themes or rely on the device's settings.</figcaption>
</figure>

This is how Terra's "Night Mode" looks like:
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +<figure class="w-figure">
```suggestion
<figure>
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +</div>
```suggestion
<ul class="stats">
  <div class="stats__item">
    <p class="stats__figure">2<sub>X</sub></p>
    <p>More pages per session</p>
  </div>
</ul>
```

2021-11-30 10:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +</div>
```suggestion
<ul class="stats">
  <div class="stats__item">
    <p class="stats_figure"><sub>60%</sub></p>
    <p>Reduction in Bounce Rates</p>
  </div>
  <div class="stats__item">
    <p class="stats__figure">170<sub>%</sub></p>
    <p>More pages per session</p>
  </div>
</ul>
```

2021-11-30 15:00 UTC, demianrenzulli commented
Thanks for reviewing this PR @rachelandrew! I just committed all your suggestions and run it locally. It seems that the components and images look good.

Please, let me know if you need anything else from me.

2021-11-30 22:07 UTC, demianrenzulli commented
Update:

@rachelandrew: I just ran the site locally again, after pulling the latest changes from `main` and merging them back to my branch. I see that the "stats" component is displayed as plain text and images appear aligned to the left, instead of centered. Would it be possible for you to double-check on your side what might be wrong?

@jpmedley: I just committed the changes for the suggestions you have made. I still need to work on the tables. I understand that you are referring to the [tables component](https://web.dev/handbook/web-dev-components/#tables), but if you have any article example to share that's using them properly that would help.

2021-12-01 09:40 UTC, andreban approved these changes
LGTM (from a Dark Theme perspective)

2021-12-03 10:32 UTC, rachelandrew approved these changes

2021-12-09 17:07 UTC, demianrenzulli commented
Hi team, thanks again for taking a look at this PR and leaving comments. It seems like we have all the approvals now.

I see that the [preview](https://deploy-preview-6898--web-dev-staging.netlify.app/terra-dark-mode/) still shows the "stats" components broken and the images are aligned to left instead of centered.

@rachelandrew: I recall you've mentioned that this will be fixed at the time of launching this (Dec 18th), is that correct? 
Even if that's the case, Is there anything we can do to be able to preview the content with the components fixed before the launch date? I'd like to share a final version with the partner, so we make sure that everything looks good.

Thanks in advance.

2021-12-17 06:35 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +    <p class="stats_figure"><sub>60%</sub></p>
```suggestion
    <p class="stats_figure">60<sub>%</sub></p>
```

2021-12-17 08:03 UTC, rachelandrew commented on src/site/content/en/blog/terra-dark-mode/index.md
> +    <p class="stats_figure">60<sub>%</sub></p>
```suggestion
    <p class="stats__figure">60<sub>%</sub></p>
```

2021-12-18 05:25 UTC, merged

2021-12-18 17:22 UTC, demianrenzulli commented
Just in case it's easier to see it here, or anyone in Web.dev side can help: 

The images are not being sized correctly in the production version of this article, due to the usage of the new component: https://web.dev/terra-dark-mode/.

The [tweet has been published earlier today](https://twitter.com/ChromiumDev/status/1472237217858957323), so If there's anything we can do to help, please, let us know.

cc // @mobtec