Adding the next five modules
GoogleChrome/web.dev pull request #6900
Opened 2021-11-29 09:51 UTC by rachelandrew

Fixes: #6409 
Fixes: #6410 
Fixes: #6411 
Fixes: #6412 
Fixes: #6413 

Adds the next five articles. To be merged as part of Designcember.

2021-11-29 14:50 UTC, adactio approved these changes
Looks good!

(I made some small formatting adjustments, as mentioned in chat.)

2021-11-30 21:14 UTC, argyleink approved these changes
nice, looks good. new page styles are nice too 👍🏻

2021-12-03 21:26 UTC, camden requested changes
Updated the heights of a couple of demos to avoid scrollbars.

2021-12-03 21:26 UTC, camden commented on src/site/content/en/learn/design/icons/index.md
> + height: 300,
```suggestion
 height: 360,
```

2021-12-03 21:26 UTC, camden commented on src/site/content/en/learn/design/theming/index.md
> + height: 400,
```suggestion
 height: 440,
```

2021-12-06 07:43 UTC, rachelandrew commented on src/site/content/en/learn/design/icons/icons.assess.yml
> +        rationale: "Unlight .png or .jpg, SVG has no need for `srcset` or a `<picture>` element."
```suggestion
        rationale: "Unlight .png or .jpg, SVG has no need for `srcset` or a `<picture>` element."
```
```suggestion
        rationale: "Unlike `.png` or `.jpg`, SVG has no need for `srcset` or a `<picture>` element."
```

2021-12-06 07:44 UTC, rachelandrew commented on src/site/content/en/learn/design/icons/icons.assess.yml
> +        rationale: "Media queries can change inline SVG styles yep!"
```suggestion
      - content: "Styleable from CSS"
        rationale: "Match SVG icon shapes to buttons and brand colors."
      - content: "No download required."
        rationale: "All the instructions are there."
      - content: "Lazy loaded by default."
        rationale: "No download to be lazy about."
      - content: "Less CPU usage."
        rationale: "I made this up."
      - content: "Light or dark themed without a new asset."
        rationale: "Media queries can change inline SVG styles!"
```

2021-12-06 07:48 UTC, rachelandrew commented on src/site/content/en/learn/design/theming/theming.assess.yml
> +        rationale: "This work too, but is a bit harder."
```suggestion
      - content: "Write a bunch of CSS to change all the defaults of the input."
        rationale: "This works too, but is a bit harder."
```

2021-12-06 07:49 UTC, rachelandrew commented on src/site/content/en/learn/design/typography/typography.assess.yml
> +      - content: "It makes the math easy"
```suggestion
      - content: "It makes the math easy."
```

2021-12-06 07:49 UTC, rachelandrew commented on src/site/content/en/learn/design/typography/typography.assess.yml
> +        rationale: "The post explicitly says don't use pixel values for `line-height`"
```suggestion
        rationale: "The post explicitly says don't use pixel values for `line-height`."
```

2021-12-06 07:50 UTC, rachelandrew commented on src/site/content/en/learn/design/typography/typography.assess.yml
> +        rationale: "Fonts cannot be hidden"
```suggestion
        rationale: "Fonts cannot be hidden."
```

2021-12-09 05:27 UTC, merged