attempt at inline figure
GoogleChrome/web.dev pull request #6936
Opened 2021-12-01 18:01 UTC by devnook

2021-12-02 14:34 UTC, hankchizljaw requested changes
Just a couple of nits, but LGTM otherwise

2021-12-02 14:34 UTC, hankchizljaw commented on src/scss/blocks/_prose.scss
> +  max-width: $global-prose-element-max-width;
We're doing to need a `display: flow-root` here too to clear any floats 👍

2021-12-02 14:34 UTC, hankchizljaw commented on src/scss/blocks/_figure.scss
> +  margin-right: var(--flow-space, 1em);
Let's replace this with `margin-inline-end: get-space('size-1')`

2021-12-02 14:34 UTC, hankchizljaw commented on src/scss/blocks/_figure.scss
> +  margin-left: var(--flow-space, 1em);
Let's replace this with `margin-inline-start: get-space('size-1')`

2021-12-03 11:42 UTC, devnook commented
ptal

2021-12-03 11:46 UTC, hankchizljaw approved these changes
LGTM. Nice one, @devnook!

2021-12-09 11:22 UTC, merged