New Post: GUI Challenges - Building a toast component
GoogleChrome/web.dev pull request #6964
Opened 2021-12-03 23:45 UTC by argyleink

Fixes #6937

Todo:
- [ ] get final reviews
- [ ] add final youtube embed

2021-12-06 09:24 UTC, rachelandrew requested changes
Just a query on date really :)

2021-12-06 09:24 UTC, rachelandrew commented on src/site/content/en/blog/building-a-toast-component/index.md
> +date: 2021-12-08
According to the Designcember spreadsheet this is for the 16th.

2021-12-06 16:23 UTC, argyleink commented on src/site/content/en/blog/building-a-toast-component/index.md
> +date: 2021-12-08
Nice, that's when Designcember features it, but it'll release at it's Google Dev Show cadence on 08. going to keep the date as is!

2021-12-08 09:24 UTC, rachelandrew approved these changes

2021-12-08 16:19 UTC, merged