Fix wrong Vitals-page to Russian translation
GoogleChrome/web.dev pull request #6965
Opened 2021-12-04 08:39 UTC by denisstasyev

Fixes some errors in translation of the [Vitals-page](https://web.dev/vitals/)

2021-12-06 16:39 UTC, malchata approved these changes

2021-12-09 16:56 UTC, lashaie08 requested changes
[#6868]()

2021-12-09 16:56 UTC, lashaie08 commented on src/site/content/ru/vitals/index.md
>  ## Обзор
#7006

2021-12-09 16:56 UTC, lashaie08 commented on src/site/content/ru/vitals/index.md
>  @``

2021-12-09 16:56 UTC, lashaie08 commented on src/site/content/ru/vitals/index.md
> -Оптимизация качества взаимодействия с пользователемключ к долгосрочному успеху любого сайта в Интернете. Web Vitals поможет владельцам бизнеса, маркетологам или разработчикам количественно оценить вп
пользователемключ #6566

2021-12-12 17:09 UTC, denisstasyev commented on src/site/content/ru/vitals/index.md
> -Оптимизация качества взаимодействия с пользователемключ к долгосрочному успеху любого сайта в Интернете. Web Vitals поможет владельцам бизнеса, маркетологам или разработчикам количественно оценить вп
Thanks for the review, but could you clarify your comments?

2022-02-17 08:58 UTC, merged