Purge CSS implementation for next.css
GoogleChrome/web.dev pull request #7059
Opened 2021-12-16 12:02 UTC by hankchizljaw

**Important** if—[as outlined in the wiki](https://github.com/GoogleChrome/web.dev/wiki/Design-system-rollout-and-removal-of-old-system#nextscss-to-be-name-changed)—the `next.css` name is changed to `main.css`, this implementation will need to be updated.

Fixes #6996

2022-04-14 13:47 UTC, devnook approved these changes

2022-04-16 06:28 UTC, devnook commented
comment test

2022-04-16 06:36 UTC, devnook commented
comment

2022-04-16 06:39 UTC, devnook commented
comment

2022-04-16 06:40 UTC, devnook approved these changes
approve comment

2022-04-16 06:41 UTC, devnook requested changes
changes comment

2022-08-17 08:23 UTC, matthiasrohmer commented
As the approach of including all CSS and purging seems to not be ideal anyway, people are used to working with next.css, the needed change [is documented](https://github.com/GoogleChrome/web.dev/wiki/Design-system-rollout-and-removal-of-old-system#nextscss-to-be-name-changed) and this PR seems to be mostly used for testing, closing once we decide to touch CSS anyway.

2022-08-17 08:23 UTC, closed without merging