[Gamepad article] Remove `GamepadList` refs
GoogleChrome/web.dev pull request #7161
Opened 2022-01-13 10:19 UTC by tomayac

Changes proposed in this pull request:

- Remove `GamepadList` refs.

2022-01-13 11:04 UTC, beaufortfrancois approved these changes
LGTM

Quick question: Did max number of characters per line rule changed?

2022-01-13 11:17 UTC, tomayac commented
> Quick question: Did max number of characters per line rule changed?

I have my prettier config set to 100, but probably didn't run prettier back when this was created.

2022-01-13 11:28 UTC, beaufortfrancois commented
@tomayac See https://github.com/GoogleChrome/web.dev/blob/main/.prettierrc.js#L4

2022-01-13 11:52 UTC, tomayac commented
I thought we use 100 for Markdown. I don't mind either way, it's just a setting. Maybe @MichaelSolati for a final word.

2022-01-13 16:33 UTC, jpmedley requested changes
Thom,

There are a couple of nits to fix. I don't want to hold up this PR, but wee need to look at shoring up MDN's documentation on this so that we can replace your reference with a link.

Joe

2022-01-14 15:05 UTC, tomayac commented on src/site/content/en/blog/gamepad/index.md
> +The browser represents gamepads as `Gamepad` objects. A `Gamepad` has the following fields:
Added the missing properties.

2022-01-18 16:45 UTC, jpmedley requested changes

2022-01-18 16:45 UTC, jpmedley commented on src/site/content/en/blog/gamepad/index.md
> +The `vibrationActuator` property returns a `GamepadHapticActuator` object, which corresponds to a
Do you mind [opening a ticket](https://github.com/mdn/browser-compat-data/issues) in the browser compat database. Here's [the JSON file](https://github.com/mdn/browser-compat-data/blob/main/api/Gamepad.json) that needs to be updated.

2022-01-19 11:19 UTC, tomayac commented on src/site/content/en/blog/gamepad/index.md
> +The `vibrationActuator` property returns a `GamepadHapticActuator` object, which corresponds to a
Will do. Can this PR land meanwhile? We can come back to it in the future.

2022-01-19 11:28 UTC, tomayac commented on src/site/content/en/blog/gamepad/index.md
> +The `vibrationActuator` property returns a `GamepadHapticActuator` object, which corresponds to a
@jpmedley FYI, chimed in on https://github.com/mdn/browser-compat-data/issues/12180.

2022-01-19 15:09 UTC, jpmedley approved these changes

2022-01-19 15:15 UTC, merged