Blog post: Embedding JavaScript snippets in C++
GoogleChrome/web.dev pull request #7162
Opened 2022-01-13 14:59 UTC by RReverser

Fixes #6891 

Changes proposed in this pull request:

-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2022-01-17 16:37 UTC, rachelandrew requested changes
Just a few small bits here.

2022-01-17 16:37 UTC, rachelandrew commented on src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
> +When working on WebAssembly integration with the web, you need a way to call out to external APIs such as web APIs and third-party libraries. You then need a way to store the values and object instan
```suggestion
When working on WebAssembly integration with the web, you need a way to call out to external APIs such as web APIs and third-party libraries. You then need a way to store the values and object instances those APIs return, and a way to pass those stored values to other APIs later. For asynchronous APIs, you might also need to await promises in your synchronous C/C++ code with [Asyncify](/asyncify/) and read the result once the operation is finished.
```

2022-01-17 16:37 UTC, rachelandrew commented on src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
> +Each `await()` also has to pause the C++ side by unwinding the entire call stack of the WebAssembly module, returning to JavaScript, waiting, and restoring the WebAssembly stack when the operation is
```suggestion
Each `await()` also has to pause the C++ side by unwinding the entire call stack of the WebAssembly module, returning to JavaScript, waiting, and restoring the WebAssembly stack when the operation is complete.
```

2022-01-17 16:37 UTC, rachelandrew commented on src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
> +The only bit left that does not look pretty is the `Asyncify.handleAsync` wrapper - its only purpose is to allow executing `async` JavaScript functions with Asyncify. In fact, this use case is so com
```suggestion
The only bit left that does not look pretty is the `Asyncify.handleAsync` wrapper—its only purpose is to allow executing `async` JavaScript functions with Asyncify. In fact, this use case is so common that there is now a specialized `EM_ASYNC_JS` macro that combines them together.
```

2022-01-17 16:37 UTC, rachelandrew commented on src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
> +Any passed arguments will be available under names `$0`, `$1`, and so on in the JavaScript body. As with `EM_JS` or WebAssembly in general, the arguments are limited only to numeric values - integers
```suggestion
Any passed arguments will be available under names `$0`, `$1`, and so on in the JavaScript body. As with `EM_JS` or WebAssembly in general, the arguments are limited only to numeric values—integers, floating-point numbers, pointers and handles.
```

2022-01-17 16:57 UTC, RReverser commented on src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
> +date: 2022-01-20
```suggestion
date: 2022-01-17
```

@rachelandrew If this is looking good otherwise, then I'm happy to publish today.

2022-01-18 11:50 UTC, RReverser commented on src/site/content/en/blog/emscripten-embedding-js-snippets/index.md
> +date: 2022-01-20
Or today :)

```suggestion
date: 2022-01-18
```

2022-01-18 14:58 UTC, rachelandrew approved these changes

2022-01-18 15:36 UTC, merged