Improve fallback pattern
GoogleChrome/web.dev pull request #7197
Opened 2022-01-19 10:42 UTC by tomayac

Fixes #7158

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2022-01-19 15:07 UTC, jpmedley requested changes

2022-01-19 15:07 UTC, jpmedley commented on src/site/content/en/blog/variable-fonts/index.md
> +not see any styling. If this is a problem, you could always use one of the
```suggestion
not show any styling. If this is a problem, you could always use one of the
```

2022-01-19 15:16 UTC, jpmedley commented on src/site/content/en/blog/variable-fonts/index.md
> +not see any styling. If this is a problem, you could always use one of the
Is there a reason you're not accepting this one?

2022-01-19 15:28 UTC, tomayac commented
Sorry, overlooked one suggestion. Accepted now. PTAL.

2022-01-20 14:54 UTC, jpmedley approved these changes

2022-01-20 15:09 UTC, merged