Mention HID Explorer tool
GoogleChrome/web.dev pull request #7203
Opened 2022-01-20 13:46 UTC by beaufortfrancois

This PR mentions the handy [HID Explorer web app](https://nondebug.github.io/webhid-explorer/) to https://web.dev/devices-introduction and https://web.dev/hid

2022-01-21 15:23 UTC, jpmedley requested changes

2022-01-21 15:23 UTC, jpmedley commented on src/site/content/en/blog/hid/index.md
> +Check out the [HID explorer][hid-explorer] web app tool for dumping HID devices
```suggestion
Check out the [HID explorer][hid-explorer] for dumping HID device
```

2022-01-21 16:57 UTC, beaufortfrancois commented
Done @jpmedley Thanks for the review!

2022-01-24 08:28 UTC, beaufortfrancois commented
Can you please approve?

2022-01-24 15:29 UTC, jpmedley approved these changes

2022-01-25 08:41 UTC, merged