Fix "schemeful same-site" translation in Japanese
GoogleChrome/web.dev pull request #7308
Opened 2022-02-05 01:49 UTC by lacolaco

Changes proposed in this pull request:

- Fix Japanese translation of "schemeful samesite" (based on https://developers-jp.googleblog.com/2020/12/chrome-same-site.html)

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

cc/ @agektmr

2022-02-05 02:26 UTC, agektmr requested changes
Can you insert a space between alphabet's and kanas?

2022-02-05 02:51 UTC, lacolaco commented
I've fixed another mistranslation about "scheme-less site-site".

2022-02-07 02:46 UTC, agektmr approved these changes
LGTM, thank you!

2022-02-07 10:59 UTC, mihajlija approved these changes

2022-02-07 11:00 UTC, merged