MigratingAuthors
GoogleChrome/web.dev pull request #7429
Opened 2022-03-02 18:05 UTC by simgobb

Added all the authors of the articles labelled as DCC in the ContentMigration Sheet

@rachelandrew

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2022-03-03 07:21 UTC, rachelandrew commented
@simgobb this is web.dev, you mentioned DCC. Can you confirm these are authors for web.dev articles not DCC?

2022-03-03 07:25 UTC, simgobb commented
@rachelandrew Yes, sorry. I confirm that these are the Web Dev ones I got from the migration sheet. 

I don't think we have any content ready yet as we focused on DCC, but I thought it would be good to sort this side of things as well to avoid the issues we had with DCC.

2022-03-03 11:19 UTC, rachelandrew commented
@simgobb it looks like these are going to need images. I think that's why it is not building. You can upload the ones used on WebFundamentals.

2022-03-07 06:48 UTC, rachelandrew requested changes
I just realised that a lot of these have a bio of "... is a contributor to WebFundamentals" can we update all of these to web.dev?

2022-03-07 06:48 UTC, rachelandrew commented on src/site/_data/i18n/authors.yml
> +    en: Mat is a contributor to WebFundamentals
```suggestion
    en: Mat is a contributor to web.dev
```

2022-03-07 06:48 UTC, rachelandrew commented on src/site/_data/i18n/authors.yml
> +    en: Ewa is a contributor to WebFundamentals
```suggestion
    en: Ewa is a contributor to web.dev
```

2022-03-07 08:56 UTC, rachelandrew approved these changes

2022-03-07 09:01 UTC, merged