Remove Duplicate Self-Assessment
GoogleChrome/web.dev pull request #7452
Opened 2022-03-05 22:49 UTC by sckimynwa

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- There are duplicate Self-assessment in this page so i removed one

![image](https://user-images.githubusercontent.com/30401400/156902285-3d398296-da45-4edc-8b77-952470ecee8b.png)

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2022-03-06 09:31 UTC, rachelandrew commented
@sckimynwa can you sign the CLA so we can merge this?

2022-03-07 15:04 UTC, jpmedley requested changes
Thank you for submitting.

2022-03-08 12:23 UTC, sckimynwa commented on src/site/content/ko/accessible/labels-and-text-alternatives/index.md
> -{% Assessment 'self-assessment' %}
@jpmedley Aha Thanks I'll change that

2022-03-08 12:30 UTC, sckimynwa commented
> @sckimynwa can you sign the CLA so we can merge this?

I signed the CLA & change things

2022-03-08 15:16 UTC, jpmedley requested changes

2022-03-08 15:16 UTC, jpmedley commented on src/site/content/ko/accessible/labels-and-text-alternatives/index.md
> +<figure>{% Img src="image/admin/WklT2ymrCmceyrGUNizF.png", alt="'홍보 제안을 수신하시겠습니까?'를 나타내는 VoiceOver 텍스트 출력", width="640", height="174" %}<br></figure>
```suggestion
<figure>{% Img src="image/admin/WklT2ymrCmceyrGUNizF.png", alt="'홍보 제안을 수신하시겠습니까?'를 나타내는 VoiceOver 텍스트 출력", width="640", height="174" %}</figure>
```

2022-08-17 16:46 UTC, jpmedley approved these changes

2022-08-17 16:46 UTC, merged