Content migration batch 6
GoogleChrome/web.dev pull request #7505
Opened 2022-03-16 10:43 UTC by mattletford

Content migration

From: https://developers.google.com/web/fundamentals/push-notifications/common-notification-patterns
To: https://web.dev/push-notifications-common-notification-patterns

From: https://developers.google.com/web/fundamentals/push-notifications/display-a-notification
To: https://web.dev/push-notifications-display-a-notification

From: https://developers.google.com/web/fundamentals/push-notifications/how-push-works
To: https://web.dev/push-notifications-how-push-works

From: https://developers.google.com/web/fundamentals/push-notifications/notification-behaviour
To: https://web.dev/push-notifications-notification-behaviour

From: https://developers.google.com/web/fundamentals/native-hardware/user-location
To: https://web.dev/push-notifications-common-issues-and-reporting-bugs

@rachelandrew

2022-03-16 16:59 UTC, rachelandrew requested changes
You should be able to go through and just commit these as a batch.

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +## Authorization Issues
```suggestion
## Authorization issues
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +### On Chrome + FCM
```suggestion
### On Chrome and FCM
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +## HTTP Status Codes
```suggestion
## HTTP status codes
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +## Payload Encryption Issue
```suggestion
## Payload encryption issue
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/g8VpxsP7PMWPSdtSvAkY.png", alt="Firefox DevTools with decryption message", width="800", height="269" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/g8VpxsP7PMWPSdtSvAkY.png", alt="Firefox DevTools with decryption message.", width="800", height="269" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/VH4juz336de2yiInKjUO.png", alt="Chrome GCM internals record", width="800", height="226" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/VH4juz336de2yiInKjUO.png", alt="Chrome GCM internals record.", width="800", height="226" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/DszP9aaiMTmX5LdTXKPx.png", alt="GCM internals decryption log", width="800", height="155" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/DszP9aaiMTmX5LdTXKPx.png", alt="GCM internals decryption log.", width="800", height="155" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +## Connection Issue
```suggestion
## Connection issue
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/vRKzAO05KD5vUpQ6nL3z.png", alt="GCM internals receive message log", width="800", height="117" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/vRKzAO05KD5vUpQ6nL3z.png", alt="GCM internals receive message log.", width="800", height="117" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/YdYj19Kn0zl6Jlfbm9hg.png", alt="GCM internals connection state", width="584", height="246" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/YdYj19Kn0zl6Jlfbm9hg.png", alt="GCM internals connection state.", width="584", height="246" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-issues-and-reporting-bugs/index.md
> +## Raising Bug Reports
```suggestion
## Raising bug reports
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-notification-patterns/index.md
> +title: Common Notification Patterns
```suggestion
title: Common notification patterns
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-notification-patterns/index.md
> +Note: We are returning the promise for `matchingClient.focus()` and
```suggestion
We are returning the promise for `matchingClient.focus()` and
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-notification-patterns/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/plgFelmhahN06Unqr2dr.png", alt="First notification without merging", width="380", height="116" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/plgFelmhahN06Unqr2dr.png", alt="First notification without merging.", width="380", height="116" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-common-notification-patterns/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/bKoZiyLJI8DVYOPQBIGv.png", alt="Second notification with merging", width="380", height="121" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/bKoZiyLJI8DVYOPQBIGv.png", alt="Second notification with merging.", width="380", height="121" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +    <ServiceWorkerRegistration>.showNotification(<title>, <options>);
```suggestion
<ServiceWorkerRegistration>.showNotification(<title>, <options>);
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/ZVIQcUqIlNerdPiqOM9C.png", alt="Dissection of the UI of a Notification", width="800", height="284" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/ZVIQcUqIlNerdPiqOM9C.png", alt="Dissection of the UI of a Notification.", width="800", height="284" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +### Title and Body Options
```suggestion
### Title and body options
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/BZnd4sFC3XMq8yPUkYVz.png", alt="Notification with title and body text on Chrome on Linux", width="380", height="117" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/BZnd4sFC3XMq8yPUkYVz.png", alt="Notification with title and body text on Chrome on Linux.", width="380", height="117" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/hyJWXo3xO7AlrlE3I61F.png", alt="Notification with title and body text on Firefox on Linux", width="521", height="74" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/hyJWXo3xO7AlrlE3I61F.png", alt="Notification with title and body text on Firefox on Linux.", width="521", height="74" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/MjZfnuD9h6MJLjv9enVi.png", alt="Notification with long title and body text on Chrome on Linux", width="380", height="156" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/MjZfnuD9h6MJLjv9enVi.png", alt="Notification with long title and body text on Chrome on Linux.", width="380", height="156" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/hyJWXo3xO7AlrlE3I61F.png", alt="Notification with long title and body text on Firefox on Linux", width="521", height="74" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/hyJWXo3xO7AlrlE3I61F.png", alt="Notification with long title and body text on Firefox on Linux.", width="521", height="74" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/Huyo4xr85SwcmPN9zSly.png", alt="Notification with long title and body text on Firefox on Linux while hovering over the notification with the mouse curso
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/Huyo4xr85SwcmPN9zSly.png", alt="Notification with long title and body text on Firefox on Linux while hovering over the notification with the mouse cursor.", width="521", height="159" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/OQRchMO68ph6UV2Lovy0.png", alt="Notification with long title and body text on Firefox on Windows", width="562", height="281" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/OQRchMO68ph6UV2Lovy0.png", alt="Notification with title and body text on Firefox on Windows.", width="562", height="281" %}

{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/OQRchMO68ph6UV2Lovy0.png", alt="Notification with long title and body text on Firefox on Windows.", width="562", height="281" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/RBQH1QGLIRT9HxJTDjkj.png", alt="Notification with icon on Chrome on Linux", width="380", height="100" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/RBQH1QGLIRT9HxJTDjkj.png", alt="Notification with icon on Chrome on Linux.", width="380", height="100" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/EoS5ydulQRjq1nxTJxrA.png", alt="Notification with icon on Firefox on Linux", width="522", height="75" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/EoS5ydulQRjq1nxTJxrA.png", alt="Notification with icon on Firefox on Linux.", width="522", height="75" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +Note: Some browsers may require the image be served over HTTPS. Be aware of this
```suggestion
Some browsers may require the image be served over HTTPS. Be aware of this
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/LaAYwycbWMn8SCro7fyo.png", alt="Notification with badge on Chrome for Android", width="800", height="248" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/LaAYwycbWMn8SCro7fyo.png", alt="Notification with badge on Chrome for Android.", width="800", height="248" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/VF32ZZXDZj2xO7dJdR3W.png", alt="Notification with image on Chrome on Linux", width="800", height="554" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/VF32ZZXDZj2xO7dJdR3W.png", alt="Notification with image on Chrome on Linux.", width="800", height="554" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/xF6oPjieHKCqtvrsWfM7.png", alt="Notification with image on Chrome for Android", width="380", height="340" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/xF6oPjieHKCqtvrsWfM7.png", alt="Notification with image on Chrome for Android.", width="380", height="340" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +
```suggestion
}

registration.showNotification(title, options);
```

```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/GI8sj9krxVtxWVeHGuvs.png", alt="Notification with actions on Chrome for Android", width="800", height="296" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/GI8sj9krxVtxWVeHGuvs.png", alt="Notification with actions on Chrome for Android.", width="800", height="296" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/REyUtJ7icGvOoepXgpLQ.png", alt="Notification with actions on Chrome on Linux", width="380", height="178" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/REyUtJ7icGvOoepXgpLQ.png", alt="Notification with actions on Chrome on Linux.", width="380", height="178" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/epWm0UDjQzcRMz37uaaa.png", alt="Notification with right-to-left language on Chrome on Linux", width="380", height="234" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/epWm0UDjQzcRMz37uaaa.png", alt="Notification with right-to-left language on Chrome on Linux.", width="380", height="234" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/ncKq2yMj7ipFkGGOWKBr.png", alt="Notification with right-to-left language on Firefox on Linux", width="521", height="102" %}
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/ncKq2yMj7ipFkGGOWKBr.png", alt="Notification with right-to-left language on Firefox on Linux.", width="521", height="102" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +Caution: Support for [`vibrate` has been deprecated](https://crbug.com/971422)
```suggestion
Support for [`vibrate` has been deprecated](https://crbug.com/971422)
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-display-a-notification/index.md
> +## Browsers and Feature Detection
```suggestion
## Browsers and feature detection
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-how-push-works/index.md
> +title: How Push Works
```suggestion
title: How push works
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-how-push-works/index.md
> +## Step 2: Send a Push Message
```suggestion
## Step 2: Send a push message
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-how-push-works/index.md
> +### Who and What is the Push Service?
```suggestion
- Who and what is the push service?
- What does the API look like? Is it JSON, XML, something else?
- What can the API do?

### Who and what is the push service?
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-how-push-works/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/f42EMdaS3bjYhIw47E1J.svg", alt="When your server wishes to send a push message, it makes a web push protocol request to a push service", width="800", he
```suggestion
{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/f42EMdaS3bjYhIw47E1J.svg", alt="When your server wishes to send a push message, it makes a web push protocol request to a push service.", width="800", height="220" %}
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-how-push-works/index.md
> +### Step 3: Push Event on the User's Device
```suggestion
### Step 3: Push event on the user's device
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-notification-behaviour/index.md
> +title: Notification Behavior
```suggestion
title: Notification behavior
```

2022-03-16 16:59 UTC, rachelandrew commented on src/site/content/en/blog/push-notifications-notification-behaviour/index.md
> +## Requires Interaction
```suggestion
## Requires interaction
```

2022-03-17 05:21 UTC, rachelandrew commented
@mattletford please follow the process detailed here to add suggestions to a batch https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request

2022-03-17 09:50 UTC, mattletford commented
@rachelandrew Thanks for the help with adding suggestions to a batch!

2022-03-17 12:10 UTC, rachelandrew approved these changes

2022-03-17 12:23 UTC, merged