Content migration batch 9
GoogleChrome/web.dev pull request #7551
Opened 2022-03-23 13:08 UTC by mattletford

Migrating content

https://developers.google.com/web/fundamentals/performance/audit/tools
https://web.dev/performance-audit-tools

https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript
https://web.dev/critical-rendering-path-adding-interactivity-with-javascript

https://developers.google.com/web/fundamentals/performance/critical-rendering-path/analyzing-crp
https://web.dev/critical-rendering-path-analyzing-crp

https://developers.google.com/web/fundamentals/performance/critical-rendering-path/constructing-the-object-model
https://web.dev/critical-rendering-path-constructing-the-object-model

https://developers.google.com/web/fundamentals/performance/critical-rendering-path/measure-crp
https://web.dev/critical-rendering-path-measure-crp

@rachelandrew

2022-03-23 16:55 UTC, rachelandrew requested changes
See comments inline

2022-03-23 16:55 UTC, rachelandrew commented on src/site/content/en/blog/performance-audit-tools/index.md
> +<br>
```suggestion
```

2022-03-29 07:47 UTC, rachelandrew commented
@mattletford this one still has a bunch of changes to tidy up so we can get it merged.

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/performance-audit-tools/index.md
> +<br><br>
@rachelandrew removed

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/performance-audit-tools/index.md
> +{% Aside %}
@rachelandrew converted to markdown

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/performance-audit-tools/index.md
> +<div class="note">
@rachelandrew converted to markdown

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/performance-audit-tools/index.md
> +<strong>Images constitute by far the
@rachelandrew converted to markdown

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/performance-audit-tools/index.md
> +<br><br>
@rachelandrew removed

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/critical-rendering-path-constructing-the-object-model/index.md
> +<img src="images/full-process.png" alt="DOM construction process">
@rachelandrew image uploaded

2022-03-29 09:55 UTC, mattletford commented on src/site/content/en/blog/critical-rendering-path-adding-interactivity-with-javascript/index.md
> +<img src="images/device-js-small.png"  alt="page preview">
@rachelandrew image uploaded

2022-03-29 12:26 UTC, rachelandrew approved these changes

2022-03-29 14:12 UTC, merged