Content migration batch 11
GoogleChrome/web.dev pull request #7555
Opened 2022-03-23 15:18 UTC by mattletford

Migrating content

https://developers.google.com/web/fundamentals/performance/get-started
https://web.dev/performance-get-started

https://developers.google.com/web/fundamentals/performance/get-started/graphicalcontent-4
https://web.dev/performance/get-started-graphicalcontent-4

https://developers.google.com/web/fundamentals/performance/get-started/httpcaching-6
https://web.dev/performance/get-started-httpcaching-6

https://developers.google.com/web/fundamentals/performance/get-started/httprequests-5
https://web.dev/performance/get-started-httprequests-5

https://developers.google.com/web/fundamentals/performance/get-started/textcontent-3
https://web.dev/performance-get-started-textcontent-3

@rachelandrew

2022-03-23 16:51 UTC, rachelandrew requested changes
There's a UR to fix in this.

2022-03-23 16:51 UTC, rachelandrew commented on src/site/content/en/blog/performance-get-started-httpcaching-6/index.md
> +[HTTP Cache](/web/fundamentals/performance/optimizing-content-efficiency/http-caching).
```suggestion
[HTTP Cache](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching).
```

2022-03-29 14:15 UTC, rachelandrew requested changes
An issue has come up when I ran tests, see the comment inline.

2022-04-01 10:20 UTC, mattletford commented on src/site/content/en/blog/performance-get-started-textcontent-3/index.md
> +```apacheapacheconf
@rachelandrew changed language name

2022-04-04 12:51 UTC, rachelandrew approved these changes

2022-04-04 12:58 UTC, merged