Add Learn PWA: Part 18, Window management.
GoogleChrome/web.dev pull request #7721
Opened 2022-04-14 18:47 UTC by jpmedley

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2022-04-14 18:54 UTC, rachelandrew commented
@jpmedley this one is failing to build due to an AVIF image being used.

2022-04-14 18:59 UTC, rachelandrew requested changes
A few little fixes and that offending image file.

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +layout: post
I don't think we use this here

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +* They have a static URL bar showing the current origin, the window's title, and a menu. Typically, they'reit's themed with the `theme_color` of your manifest.
```suggestion
* They have a static URL bar showing the current origin, the window's title, and a menu. Typically, it's themed with the `theme_color` of your manifest.
```

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/0SsThiNz4GDkJy6OiTHj.png", alt="An in-app browser on a desktop PWA when browsing a URL that is out-of-scope", width="800", height="497" %}
```suggestion
{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/0SsThiNz4GDkJy6OiTHj.png", alt="An in-app browser on a desktop PWA when browsing a URL that is out-of-scope.", width="800", height="497" %}
```

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/Gr4qJUx6hAFMyPLPyfQY.png", alt="An in-app browser on an iPhone when browsing a URL that is out-of-scope within a standalone PWA", width="800", height="3
```suggestion
{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/Gr4qJUx6hAFMyPLPyfQY.png", alt="An in-app browser on an iPhone when browsing a URL that is out-of-scope within a standalone PWA.", width="800", height="370" %}
```

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/UyohW4R5Sy79ffHri8cz.png", alt="An in-app browser on Android when browsing a URL that is out-of-scope within a standalone PWA", width="800", height="164
```suggestion
{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/UyohW4R5Sy79ffHri8cz.png", alt="An in-app browser on Android when browsing a URL that is out-of-scope within a standalone PWA.", width="800", height="1644" %}
```

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/CURym4RD66CqcTw4iPl5.png", alt="The same installed PWA with several windows opened on a desktop operating system", width="800", height="580" %}
```suggestion
{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/CURym4RD66CqcTw4iPl5.png", alt="The same installed PWA with several windows opened on a desktop operating system.", width="800", height="580" %}
```

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +You can read more about this experimental capability at (Tabbed application mode for PWA [/tabbed-application-mode/]
```suggestion
You can read more about this experimental capability at [Tabbed application mode for PWA](/tabbed-application-mode/).
```

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/9azCEwKziNBBxrTOn3pn.avif", alt="With windows control overlay, you can render content in the title bar", width="800", height="544" %}
here's the avif

2022-04-14 18:59 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/9azCEwKziNBBxrTOn3pn.avif", alt="With windows control overlay, you can render content in the title bar", width="800", height="544" %}
```suggestion
{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/9azCEwKziNBBxrTOn3pn.avif", alt="With windows control overlay, you can render content in the title bar.", width="800", height="544" %}
```

2022-04-14 19:01 UTC, jpmedley commented
I don't know where the images are located.

2022-04-14 19:53 UTC, rachelandrew commented
@jpmedley I downloaded it and made a PNG:

{% Img src="image/kheDArv5csY6rvQUJDbWRscckLr1/B5UDAJzKTqCRdSy6B5is.png", alt="ALT_TEXT_HERE", width="800", height="544" %}

2022-04-14 21:55 UTC, jpmedley commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/9azCEwKziNBBxrTOn3pn.avif", alt="With windows control overlay, you can render content in the title bar", width="800", height="544" %}
I have no way to get that.

2022-04-15 03:46 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/9azCEwKziNBBxrTOn3pn.avif", alt="With windows control overlay, you can render content in the title bar.", width="800", height="544" %}
```suggestion
{% Img src="image/kheDArv5csY6rvQUJDbWRscckLr1/B5UDAJzKTqCRdSy6B5is.png", alt="With windows control overlay, you can render content in the title bar.", width="800", height="544" %}
```

2022-04-15 04:06 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +Calling `open()` within a PWA window on iOS or iPadOS returns `null` and doesn't open a window. Opening new windows on Android creates a new in-app browser for the URL—even if the URL is within the s
```suggestion

Calling `open()` within a PWA window on iOS or iPadOS returns `null` and doesn't open a window. Opening new windows on Android creates a new in-app browser for the URL—even if the URL is within the scope of your PWA—that typically doesn't trigger an external browsing experience.
```

2022-04-15 04:06 UTC, rachelandrew commented on src/site/content/en/learn/pwa/windows/index.md
> +{% Img src="image/RK2djpBgopg9kzCyJbUSjhEGmnw1/9azCEwKziNBBxrTOn3pn.avif", alt="With windows control overlay, you can render content in the title bar", width="800", height="544" %}
I fixed it :)

2022-04-15 04:17 UTC, rachelandrew approved these changes

2022-04-15 04:18 UTC, rachelandrew commented
@jpmedley and this one is ready too - thank you!

2022-04-15 15:14 UTC, merged