Allow demos to declare their own static files
GoogleChrome/web.dev pull request #7875
Opened 2022-05-10 11:48 UTC by devnook

2022-05-10 14:34 UTC, jeffposnick requested changes
You know a lot more about our 11ty build process and patterns than I do, so I'm happy to defer to your judgment about the general approach.

I just had some general comments about tweaks to the code.

2022-05-11 09:54 UTC, devnook commented on .eleventy.js
> +  for (const patternId in patterns) {
It can, but why would that be better?

2022-05-11 09:55 UTC, devnook commented on .eleventy.js
> +    if (pattern.static && pattern.static.length) {
Old habits die hard:)

2022-05-11 14:23 UTC, jeffposnick approved these changes

2022-05-17 11:58 UTC, merged