Article Update: Profiling Web Audio apps in Chrome
GoogleChrome/web.dev pull request #8101
Opened 2022-06-06 23:08 UTC by hoch

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

- Added a new section on the new DevTools extension for Web Audio
- Fixed outdated information.

When you're ready to submit your PR, don't forget to add the `$-presubmit` label.

2022-06-08 07:26 UTC, beaufortfrancois reviewed
@hoch I've uploaded images and added some suggestions. Hope it helps.

2022-06-08 07:26 UTC, beaufortfrancois commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +{% Img src="", alt="", width="800", height="" %}
```suggestion
{% Img src="image/vvhSqZboQoZZN9wBvoXq72wzGAf1/JUXLwtX83TOXqRHD2CGU.png", alt="Screenshot showing how to open Web Audio panel in Chrome DevTools.", width="800", height="201" %}

2022-06-08 07:26 UTC, beaufortfrancois commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +### Context Selector
```suggestion
{% Img src="image/vvhSqZboQoZZN9wBvoXq72wzGAf1/4xQhLJBdDWW3X2nIssIS.png", alt="Screenshot of the Web Audio panel in Chrome DevTools", width="800", height="416" %}

### Context Selector
```

2022-06-08 07:26 UTC, beaufortfrancois commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +Since a page can have multiple BaseAudioContexts, this drop-down menu allows you
```suggestion
Since a page can have multiple `BaseAudioContexts`, this drop-down menu allows you

2022-06-08 07:26 UTC, beaufortfrancois commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +[file a bug on crbug.com][r-file-a-bug] or on the
```suggestion
[file a bug on crbug.com][cr-file-a-bug] or on the

2022-06-13 17:37 UTC, hoch commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +{% Img src="", alt="", width="800", height="" %}
Thanks! Done.

2022-06-13 17:37 UTC, hoch commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +### Context Selector
Done.

2022-06-13 17:37 UTC, hoch commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +Since a page can have multiple BaseAudioContexts, this drop-down menu allows you
Done.

2022-06-13 17:37 UTC, hoch commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +[file a bug on crbug.com][r-file-a-bug] or on the
Done.

2022-06-13 17:38 UTC, hoch commented
Thank you for your help, @beaufortfrancois! I fixed the image URLs and the draft is ready for the next round of review.

2022-06-14 06:13 UTC, beaufortfrancois reviewed
It looks good to me.
@jpmedley will be the one with the final approval.

2022-06-14 06:15 UTC, beaufortfrancois commented
@jpmedley I'm not sure https://deploy-preview-8101--web-dev-staging.netlify.app/ does not work though. Any idea?

2022-06-14 14:34 UTC, jpmedley commented
> @jpmedley I'm not sure https://deploy-preview-8101--web-dev-staging.netlify.app/ does not work though. Any idea? Maybe we need to hit "Ready for review".

It hasn't been generated yet. You can tell because there's no entry about it in the conversation tab. You'll need to click Read for review. Please do that before I review. I need to look at the rendered article as well as reviewing it.

2022-06-14 19:10 UTC, jeffposnick commented
I'm at a loss. I'm going to try closing and then re-opening the PR, as sometimes that could jolt GitHub Actions into behaving as expected.

2022-06-14 19:50 UTC, jeffposnick commented
It was due to https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy, and I had to manually approve the Netlify deploy.

I don't think we need to have that policy enabled for deploys from forks, since we shouldn't have any sensitive environment variables in our Netlify staging builds. I'll confer with Ewa and maybe we can change that setting. (This also might have been a recent change, because I don't remember having to do this in the past.)

2022-06-14 20:38 UTC, jpmedley commented
@beaufortfrancois Are you ready for my review?

2022-06-15 13:39 UTC, beaufortfrancois commented
> @beaufortfrancois Are you ready for my review?

hoch@ is the author of this post update. I've simply helped with image uploads.

2022-06-15 14:44 UTC, hoch commented
@jpmedley We already did a pass in a draft doc, but if you want to review the content once more that's fine as well!

2022-06-15 14:51 UTC, jpmedley commented
The bulk of the work is in Google Docs, but it can't merge until it has a writing team sign-off. I have to make sure all the markdown looks right. For instance, in another PR, I found a link that wasn't formatted right.

2022-06-22 14:40 UTC, jpmedley requested changes
I know you guys are anxious to get this out, but when you change it this much, I have to re-review.

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +understanding a underlying problem, so Chromium engineers will often ask it
```suggestion
understanding an underlying problem, so Chromium engineers will often ask it
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +instructions for tracing is available [here](chromium-tracing).
```suggestion
instructions for tracing are available [here](chromium-tracing).
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +performs in real time. The audio graph, a network of AudioNode objects to
```suggestion
performs in real time. The audio graph, a network of `AudioNode` objects to
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +topology is opaque by design. (Web Audio API doesn’t have features for
```suggestion
topology is opaque by design. (The Web Audio API doesn’t have features for
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +* If you find this problem, [file an issue on crbug.com](https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EWebAudio)
```suggestion
* If you find a problem, [file an issue on crbug.com](https://bugs.chromium.org/p/chromium/issues/entry?components=Blink%3EWebAudio) 
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +## Use Web Audio DevTools Extension
```suggestion
## Use the Web Audio DevTools extension
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +You also can use the DevTools extension specifically designed for Web Audio API.
```suggestion
You can also use the DevTools extension specifically designed for the Web Audio API.
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +This extension needs to be installed from
```suggestion
This extension needs to be installed from the
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +{% Img src="image/vvhSqZboQoZZN9wBvoXq72wzGAf1/4xQhLJBdDWW3X2nIssIS.png", alt="Screenshot of the Web Audio panel in Chrome DevTools", width="800", height="416" %}
```suggestion
{% Img src="image/vvhSqZboQoZZN9wBvoXq72wzGAf1/4xQhLJBdDWW3X2nIssIS.png", alt="Screenshot of the Web Audio panel in Chrome DevTools.", width="800", height="416" %}
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +Since a page can have multiple `BaseAudioContext`s, this drop-down menu allows you
```suggestion
Since a page can have multiple `BaseAudioContext` objects, this drop-down menu allows you
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +to choose the context you want to inspect. You can also manually trigger garbage
```suggestion
choosing the context you want to inspect. You can also manually trigger garbage
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +This side panel shows various properties of a user-selected context or
```suggestion
The side panel shows various properties of a user-selected context or
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +This status bar at the bottom is only active when the selected BaseAudioContext
```suggestion
The status bar at the bottom is only active when the selected `BaseAudioContext`
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +is an AudioContext, which runs in real-time. This bar shows the instantaneous
```suggestion
is an `AudioContext`, which runs in real-time. This bar shows the instantaneous
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +audio stream quality of a selected AudioContext and is updated every second. It
```suggestion
audio stream quality of a selected `AudioContext` and is updated every second. It
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +  quality. (See the example 3 above)
```suggestion
  quality. (See example 3, above.)
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +  should consider doing less (e.g. using fewer `AudioNodes` in the
```suggestion
  should consider doing less (e.g. using fewer `AudioNode` objects in the
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +clicking the "three dots" menu in the top right corner of DevTools, then go to
```suggestion
clicking the "three dots" menu in the top right corner of DevTools, then going to
```

2022-06-22 14:40 UTC, jpmedley commented on src/site/content/en/blog/profiling-web-audio-apps-in-chrome/index.md
> +**More tools** then **WebAudio**.
```suggestion
**More tools**, then **WebAudio**.
```

2022-06-22 14:58 UTC, hoch commented
Done - Not anxious at all! I just want to keep things moving. Thank you so much for the review! 🙂

2022-06-22 15:35 UTC, jpmedley approved these changes

2022-06-27 17:02 UTC, hoch commented
@jpmedley @beaufortfrancois IIUC this PR is approved. What's our next step here?

2022-06-28 07:14 UTC, merged