Add css-individual-transform-properties blogpost (Fix #8244)
GoogleChrome/web.dev pull request #8375
Opened 2022-07-20 16:08 UTC by bramus

This PR adds the `css-individual-transform-properties` blogpost, as described in https://github.com/GoogleChrome/web.dev/issues/8244

2022-07-20 16:57 UTC, bramus commented
Had to bump up the version of `@mdn/browser-compat-data` used, as the compat table shown relies on https://github.com/mdn/browser-compat-data/pull/16816 which is included in its 5.1.4 release.

2022-07-21 07:48 UTC, rachelandrew commented
@bramus can you do the compat data in a new PR? As this post will go out later than my new on the web platform post (which is when I normally update BCD). Also sometimes updating BCD breaks things so it's better alone.

2022-07-21 07:57 UTC, rachelandrew requested changes
Changes requested inline, also as mentioned in a comment can we make the BCD update as a separate PR.

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +date: 2022-08-02
```suggestion
date: 2022-08-02
tags:
  - blog
  - newly-interoperable
```

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +date: 2022-08-02
It won't show up on the blog without the blog tag.

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +description: >
We need a hero image and alt text. https://web.dev/handbook/use-media/

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +
Add the aside as in this post https://web.dev/transformstream/

I'll go through and tidy these up once we're not "newly interoperable" any more, as I can find them via the newly-interoperable tag.

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +## Order Matters
```suggestion
## Order matters
```

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +That means both code snippets below yield the same result:
```suggestion
That means both of the following code snippets give the same result:
```

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +{% Img src="image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/Pn0t3nrqfBg6JhmYFslm.svg", alt="Keyframes Graph", width="800", height="745" %}
```suggestion
{% Img src="image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/Pn0t3nrqfBg6JhmYFslm.svg", alt="Keyframes graph.", width="800", height="745" %}
```

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +{% Img src="image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/AF5n6UlhcuQ5UNKemX8M.svg", alt="Keyframes Graph with intermediate values calculated", width="800", height="745" %}
```suggestion
{% Img src="image/AeNB0cHNDkYPUYzDuv8gInYA9rY2/AF5n6UlhcuQ5UNKemX8M.svg", alt="Keyframes graph with intermediate values calculated.", width="800", height="745" %}
```

2022-07-21 07:57 UTC, rachelandrew commented on src/site/content/en/blog/css-individual-transform-properties/index.md
> +{% Codepen {
I need to send you the web.dev CodePen login details, as it's better they are in there as then anyone can update them if needed. Just fork yours into the account.

2022-07-22 10:10 UTC, bramus commented
Added the requested changes.

2022-08-02 06:07 UTC, rachelandrew approved these changes

2022-08-02 06:20 UTC, merged