Add css-border-animations blogpost
GoogleChrome/web.dev pull request #8428
Opened 2022-07-28 23:37 UTC by bramus

Fixes: https://github.com/GoogleChrome/web.dev/issues/8417

This PR adds the `css-border-animations` blogpost, as proposed in https://github.com/GoogleChrome/web.dev/issues/8417

Changes when compared to the draft:

- Updated publication date
- Moved demos to the `web-dot-dev` CodePen account
- Rewrote section on stretching the backgrounds
- Added a hero image

I see in the calendar that the “New to the Web Platform” post is also scheduled for the set date. Feel free to move this post further down the schedule.

2022-07-29 12:59 UTC, rachelandrew requested changes
Couple of things and I suggest we go with this one on Monday. The preview isn't building due to an error that has nothing to do with this post, but I built it locally to check it.

2022-07-29 12:59 UTC, rachelandrew commented on src/site/content/en/blog/css-border-animations/index.md
> +date: 2022-07-29
```suggestion
date: 2022-08-01
```

2022-07-29 12:59 UTC, rachelandrew commented on src/site/content/en/blog/css-border-animations/index.md
> +date: 2022-07-29
let's do this one Monday, it's a better day for traffic anyway.

2022-07-29 12:59 UTC, rachelandrew commented on src/site/content/en/blog/css-border-animations/index.md
> +title: CSS Border Animations
```suggestion
title: CSS border animations
```

2022-07-29 12:59 UTC, rachelandrew commented on src/site/content/en/blog/css-border-animations/index.md
> +{% Codepen {
Add a caption for this one too?

2022-07-29 13:10 UTC, bramus commented
.done

Also rewrote two sentences in 8cdd6a8

2022-08-01 06:54 UTC, rachelandrew commented on src/site/content/en/blog/css-border-animations/index.md
> +- The `border-image` does not follow the `border-radius`; it will always remain rectangular
```suggestion
- The `border-image` does not follow the `border-radius`; it will always remain rectangular.
```

2022-08-01 11:48 UTC, rachelandrew approved these changes

2022-08-01 13:18 UTC, merged