Removes mention of the web-vitals next tag in the INP documentation.
GoogleChrome/web.dev pull request #8593
Opened 2022-08-24 18:56 UTC by malchata

Changes proposed in this pull request:

- Now that the `web-vitals` JS library is out of beta, we can remove mentions of it in articles.

2022-08-24 18:56 UTC, malchata commented
Not sure which other pages refer to `web-vitals@next`. The INP doc was the only one I could find so far.

2022-08-24 18:58 UTC, tunetheweb approved these changes

2022-08-24 18:59 UTC, philipwalton requested changes
Line 192 also needs to be updated to just point to the main branch:

> See the [`onINP()`](https://github.com/GoogleChrome/web-vitals/tree/next#oninp) reference documentation for additional usage instructions.

This link to here: https://github.com/GoogleChrome/web-vitals#oninp

2022-08-24 18:59 UTC, philipwalton commented on src/site/content/en/metrics/inp/index.md
> +Writing your own [`PerformanceObserver`](https://developer.mozilla.org/docs/Web/API/PerformanceObserver) to measure INP can be difficult. To measure INP in JavaScript, it's advised that you use the `
Can you add a link to the web-vitals JS library here?

2022-08-24 19:00 UTC, tunetheweb commented
That's the only one I could find on web.dev.

Did find this on DCC though: https://developer.chrome.com/blog/inp-tools-2022/#:~:text=web%2Dvitals%40next%20includes%20INP%20support

2022-08-24 23:37 UTC, philipwalton commented
Looks like there's also an occurrence on line 156:

> - [`web-vitals` JavaScript library](https://github.com/GoogleChrome/web-vitals/tree/next).

2022-08-26 16:53 UTC, philipwalton approved these changes

2022-08-26 16:54 UTC, merged