Adding chrometober banner
GoogleChrome/web.dev pull request #8871
Opened 2022-10-14 22:27 UTC by tropicadri

Adding the chrometober banner to direct people to the content.

2022-10-15 15:46 UTC, rachelandrew requested changes
I'm not happy with the container queries working across all browsers wording, because they don't. That's a confusing message.

2022-10-17 15:07 UTC, una commented
+1, we also removed the CQ dependency in Chrometober

2022-10-17 18:32 UTC, tropicadri commented
Thank you @rachelandrew and @una sending it to Harleen to update it!

2022-10-18 10:56 UTC, rachelandrew approved these changes

2022-10-18 10:57 UTC, merged