Last baseline interop post
GoogleChrome/web.dev pull request #9612
Opened 2023-02-17 16:44 UTC by rachelandrew

2023-02-17 16:59 UTC, rachelandrew commented
@AaronForinton can you do a quick review of this for me? :)

2023-02-17 19:36 UTC, AaronForinton requested changes

2023-02-17 19:36 UTC, AaronForinton commented on src/site/content/en/blog/last-baseline/index.md
> +If you set the value of `align-items` to `baseline`, the result will be first baseline alignment. Therefore the first baseline of the item you are aligning (described as the _alignment subject_) will
```suggestion
If you set the value of `align-items` to `baseline`, the result will be first baseline alignment. Therefore the first baseline of the item you are aligning (described as the _alignment subject_) will align with the first baseline of the other items in the group. You can see this in the following example, where the first two flex items are aligned using `align-items: baseline`, so they align along the baseline created by the larger text. The final item is aligned to `flex-start` and therefore aligns to the start of the flex container.
```

2023-02-17 19:36 UTC, AaronForinton commented on src/site/content/en/blog/last-baseline/index.md
> +When aligning a grid or flex item with the value `last baseline`, the last baseline of that item will align to the last baseline of the _baseline sharing group_ that it is part of. The following exam
```suggestion
When aligning a grid or flex item with the value `last baseline`, the last baseline of that item will align to the last baseline of the _baseline sharing group_ that it is part of. The following example demonstrates last baseline alignment, with the first flex item aligning with the last line of text in the larger item. The final item in this group is aligned to `flex-end`, which is the end of the flex container.
```

2023-02-17 19:37 UTC, AaronForinton commented
@rachelandrew Just two tiny suggestions, I'll approve as soon as you've seen them.

2023-02-20 10:05 UTC, rachelandrew commented on src/site/content/en/blog/last-baseline/index.md
> +date: 2023-02-17
```suggestion
date: 2023-02-20
```

2023-02-20 10:24 UTC, merged