feat: clean up old design system `w-tooltip` class
GoogleChrome/web.dev pull request #9764
Opened 2023-03-13 11:20 UTC by mamieorine

Fixes #9711 

Changes proposed in this pull request:

- Clean up old design system `w-tooltip` class and updated to new design system Tooltip.
- Remove a stylesheet for `w-tooltip`

2023-03-14 15:13 UTC, jimjiminyjimjim reviewed
LGTM

2023-03-14 17:12 UTC, mamieorine commented
I made changes on `header-default.njk` and  `navigation-drawer-default.njk` since I spotted these templates are using old design system `w-tooltip`. However, those templates will be removed in [this PR](https://github.com/GoogleChrome/web.dev/pull/9720) and [9702](https://github.com/GoogleChrome/web.dev/issues/9702) anyway because they are unused templates.

2023-03-15 11:04 UTC, matthiasrohmer requested changes

2023-03-15 11:04 UTC, matthiasrohmer commented on src/lib/components/CopyCode/index.js
> +      this.tooltip.setAttribute('data-alignment', 'right');
I think we should keep `this.tooltip.setAttribute('role', 'tooltip');`. This is needed for proper a11y.

2023-03-15 11:04 UTC, matthiasrohmer commented on src/site/_includes/components/Tooltip.js
> +    <span class="tooltip" data-alignment="${alignment}">
Let's remove this component instead. I don't see the need for an author to use this in Markdown documents. Searching for `{% Tooltip` inside the codebase seems to show it also isn't used currently.

2023-03-15 13:25 UTC, mamieorine commented
@matthiasrohmer  I have resolved all requested changes. Thank you!

2023-03-15 13:41 UTC, matthiasrohmer approved these changes

2023-03-15 13:42 UTC, merged